src/Quartz/TriggerBuilder.cs

Update TriggerBuilder.UsingJobData(JobDataMap newJobDataMap) behavior to match that of TriggerBuilder.UsingJobData(string key, T value) overloads.  When duplicate key is found use value from newJobDataMap.

TriggerBuilder.UsingJobData(JobDataMap newJobDataMap) should ovewrite existing

---

src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs

Mimicked Trigger insert behavior. Null reading is already safe.
Fixes #269

Store null JobData in JobDetails if it's empty

---

src/Quartz/Impl/Triggers/AbstractTrigger.cs

When it invokes startTimeUtc = new DateTime(value.Year, value.Month, value.Day, value.Hour, value.Minute, value.Second), it creates time value in current TimeZone, but not in UTC.

AbstractTrigger.StartTimeUtc setter loses UTC offset information

---

src/Quartz/Core/QuartzSchedulerThread.cs

`Task.Factory.StartNew` with async delegate returns `Task<Task>`, you have to call `.Unwrap()`. For majority of cases `Task.Run` is the safer option.

Use `Task.Run` inside `QuartzSchedulerThread`

---

Quartz.build
src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj
src/Quartz.Tests.Integration/packages.config
src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj
src/Quartz.Tests.Unit/packages.config

I could not compile it locally since it complained it couldn't find the `odp.net.managed.121.1.1` nuget package. I updated now to the official managed client from oracle.

Oracle client update

---

src/Quartz.Examples/example11/SimpleJob.cs
src/Quartz.Examples/example16/AsyncJob.cs
src/Quartz.Examples/example7/DumbInterruptableJob.cs
src/Quartz.Tests.Unit/Plugin/History/LoggingJobHistoryPluginTest.cs
src/Quartz/Core/QuartzScheduler.cs
src/Quartz/ICancellableJobExecutionContext.cs
src/Quartz/IInterruptableJob.cs
src/Quartz/IJobExecutionContext.cs
src/Quartz/Impl/JobExecutionContextImpl.cs
src/Quartz/Quartz.csproj

Connects to #331 
This gets rid of `IInterruptableJob` in favour of CancellationToken. The CancellationToken is available on the job execution context and can be queried for cancellation and/or passed into the async methods supporting cancellation. For separation of concerns, I introduced a `ICancellableJobExecutionContext` which allows canceling a job.
There is one TODO. I'd argue we could remove the try/catch. But since the member `cancel` is virtual should we leave it? 
https://github.com/quartznet/quartznet/pull/339/files#diff-3670816342511c486ea84cb94c3ef967R491
Currently based on top of #336, will rebase when those are merged

Interruptable job

---

src/Quartz.Tests.Unit/Impl/DirectSchedulerFactoryTest.cs
src/Quartz/Impl/DirectSchedulerFactory.cs

This caught me badly on the quartz 3 branch. Master already has the `dbFailureRetryInterval` lingering around although no longer used. This then introduced to [a recursive call on the current 3.0 branch](https://github.com/quartznet/quartznet/blob/quartznet-3/src/Quartz/Impl/DirectSchedulerFactory.cs#L233) which leads to a StackOverflowException.

Removed dbFailureRetryInterval since it is no longer used

---

src/Quartz/Core/JobRunShell.cs
src/Quartz/Core/QuartzScheduler.cs

Connects to #331 
Gets rid of the blocking calls in the `JobRunShell`
Based on #339, will rebase when merged.

Removed `GetAwaiter().GetResult()` calls from `JobRunShell`

---

src/Quartz/Util/TimeZoneUtil.cs

"Couldn't retrieve trigger: Exception of type 'System.TimeZoneNotFoundException' was thrown."
added timezone alias to fix this

System.TimeZoneNotFoundException fix

---

src/Quartz/Simpl/SimpleThreadPool.cs

Bit of a long story (which I can share if interested), but I really need to intercept the creation of `WorkerThread` instances in `SimpleThreadPool`. Hopefully an uncontroversial change.

Create WorkerThread in virtual method

---

src/Quartz.Tests.Unit/DaylightSavingTimeTests.cs
src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj
src/Quartz/CronExpression.cs
src/Quartz/DailyTimeIntervalScheduleBuilder.cs
src/Quartz/DateBuilder.cs
src/Quartz/Impl/Triggers/CalendarIntervalTriggerImpl.cs
src/Quartz/Impl/Triggers/DailyTimeIntervalTriggerImpl.cs
src/Quartz/Util/TimeZoneUtil.cs

This PR addresses the challenges of scheduling a daily event when considering daylight saving time transitions.
First, it's worth pointing out that the Quartz.net documentation's description of how DST is handled is wrong.  It states multiple times ([in the FAQ here](http://www.quartz-scheduler.net/documentation/faq.html#daylight-saving-time-and-triggers), [in the CronTrigger Tutorial here](http://www.quartz-scheduler.net/documentation/quartz-2.x/tutorial/crontrigger.html#notes), [in the Best Practices here](http://www.quartz-scheduler.net/documentation/best-practices.html#daylight-savings-time), and probably in the API docs somewhere) that an occurrence in the spring-forward gap could be _skipped_ and an occurrence in the fall-back overlap could execute _twice_.  **This is not actually …

Handle DST better

---

readme.txt

apidoc.quartz-scheduler.net doesn't exist.

Update documentation link

---

.vscode/launch.json
Quartz.sln
src/Quartz.Web/Api/CalendarsController.cs
src/Quartz.Web/Api/Dto/CalendarDetailDto.cs
src/Quartz.Web/Api/JobsController.cs
src/Quartz.Web/Api/SchedulerController.cs
src/Quartz.Web/Api/ServerController.cs
src/Quartz.Web/Api/TriggersController.cs
src/Quartz.Web/History/DatabaseExecutionHistoryPlugin.cs
src/Quartz.Web/History/JobExecutionHistoryController.cs
src/Quartz.Web/History/JobHistoryDelegate.cs
src/Quartz.Web/LiveLog/LiveLogHub.cs
src/Quartz.Web/LiveLog/LiveLogPlugin.cs
src/Quartz.Web/Program.cs
src/Quartz.Web/Properties/AssemblyInfo.cs
src/Quartz.Web/Quartz.Web.csproj
src/Quartz.Web/Startup.cs
src/Quartz.Web/WebConsolePlugin.cs

Hi Marko,
I have converted the Quartz.Web project to asp.net core 2.0. 
- Project compiles and it has been added to the Quartz.sln file
- Swagger works on localhost:5000/swagger
- SignalR is commented out for it is not included yet in the official asp.net core release
- Index.html is hosted by default, but it does not show anything but the title. I am not a web expert so I have not touched any of the web files in /App

Fix for #477:  converted Quartz.Web project to asp.net core 2.0

---

src/Quartz/Util/TimeZoneUtil.cs

Add timeZoneIdAliases for Asia/Karachi and Pakistan Standard Time.

timeZoneIdAliases for +5 timeZone

---

src/Quartz/Impl/StdSchedulerFactory.cs
src/Quartz/Listener/BroadcastJobListener.cs

- Prevent faulty JobListeners from influencing QuartzNet logic.
- Do not always trust ReSharper to use properties with expression bodies.
See the TestRemoting -> Test method, I call the StdSchedulerFactory overthere twice and the second call would raise an exception that the remoteinstance scheduler already existed.

2 fixes for QuartzNet

---

src/Quartz/Listener/SchedulerListenerSupport.cs

It seems `JobInterrupted` had the wrong signature in the `SchedulerListenerSupport` class, it was impossible to execute logic on job interruption.
This very simple commit marks the method `virtual` so inheritors could override it.

Make JobInterrupted method virtual in class SchedulerListenerSupport

---

src/Quartz/Impl/AdoJobStore/IDriverDelegate.cs
src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs
src/Quartz/Impl/AdoJobStore/StdAdoConstants.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs

I've identified a race condition in `JobStoreSupport.AcquireNextTrigger()` that is causing duplicate trigger firings in a cluster of Quartz.Net 3.0.6 scheduler instances when under load.
I'm using the `JobStoreTX` job store with `AdoJobStore.SqlServerDelegate`.
The duplicate firing occurs when a scheduler instance gets delayed in `JobStoreSupport.AcquireNextTrigger()` between the calls to `SelectTriggerToAcquire()` and `UpdateTriggerStateFromOtherState()`. Suppose that the same trigger was simultaneously returned by `SelectTriggerToAcquire()` in two scheduler instances (A and B). If the firing of the trigger completes in instance A before `UpdateTriggerStateFromOtherState()` is called in instance B, then instance B will perform a duplicate firing.
This happens because instance A will have …

Fix a race condition that could cause duplicate trigger firings

---

src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs

#658 - Modified to SkipStringPropertySerialization for DirectoryScanJob

fixes #658 - Allow binary serialization for DirectoryScanJob data

---

src/Quartz/Simpl/RAMJobStore.cs
src/Quartz/Util/SortedSetExtensions.cs

* Update `RAMJobStore.AcquireNextTriggers()` to reduce allocations when the store has no triggers.
* Use return value of `SortedSet.Add()` to determine whether a trigger was already acquired for a job that does not allow concurrent execution.
* Use hand-rolled `FirstOrDefault()` extension method for **SortedSet** to eliminate type checks.
I only have a benchmark result for the last change (as `RAMJobStore.AcquireNextTriggers()` is hard to benchmark as it changes state):
|                    Method |     Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|-------------------------- |---------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
|       FirstOrDefault_Linq | 216.3 ns | 0.5124 ns | 0.4793 ns | …

Update RAMJobStore.AcquireNextTriggers() to reduce allocations

---

src/Quartz/Simpl/RAMJobStore.cs

* Reduced usage of **ConcurrentDictionary** in **RAMJobStore** since we always operate in a synchronized block.
* Use return value of `Dictionary.TryGetValue(TKey key, out TValue value)` and `List<T>.Remove(T value)`.
Fixes #715.
**Note:**
I could not change **triggersByKey** to a regular **Dictionary**, as there's no replacement for `ConcurrentDictionary.TryRemove(TKey key, out TValue value)`. The `Dictionary.Remove(TKey, out TValue value)` method is only available in **.NET Core** and **.NET Standard 2.1**.

Reduced usage of ConcurrentDictionary in RAMJobStore

---

src/Quartz/Simpl/TaskSchedulingThreadPool.cs

In `TaskSchedulingThreadPool.RemoveTaskFromRunningList(Task completedTask)`, do not first check if the completed task is null and in the list of running tasks. The task should never be null and always be in the list of running tasks, and, even if this does happen, invoking `runningTasks.Remove(completedTask)` with a null task is not a problem.
In `TaskSchedulingThreadPool.Shutdown(bool)` use the actual number of threads that we wait on in the log message. This also ensures we always access **runningTasks** in a synchronized block.
Remove an extra allocation in `TaskSchedulingThreadPool.Shutdown(bool)`.

Minor optimizations for TaskSchedulingThreadPool

---

src/Quartz/CronExpression.cs

It seems strange that public functions that are just TODOs would return null instead of throwing an exception, as this can be confusing for users who would expect the functionality to exist. Is there a particular reason this has been left as null?

GetTimeBefore() and GetFinalFireTime() throw NotImplementedException

---

src/Quartz/Impl/AdoJobStore/AdoJobStoreUtil.cs
src/Quartz/Impl/AdoJobStore/CronTriggerPersistenceDelegate.cs
src/Quartz/Impl/AdoJobStore/DBSemaphore.cs
src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs
src/Quartz/Impl/AdoJobStore/SimplePropertiesTriggerPersistenceDelegateSupport.cs
src/Quartz/Impl/AdoJobStore/SimpleTriggerPersistenceDelegate.cs
src/Quartz/Impl/AdoJobStore/StdAdoConstants.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs
src/Quartz/Impl/AdoJobStore/StdRowLockSemaphore.cs
src/Quartz/Impl/AdoJobStore/UpdateRowLockSemaphore.cs
src/Quartz/Impl/AdoJobStore/UpdateRowLockSemaphoreMOT.cs

Running multiple schedulers against a single database results in high cpu due to multiple query plans being created,
by adding the scheduler name as a sql parameter, sql server is able to reuse the plans across multiple schedulers.
The SchedulerNameLiteral property available on a number of classes is no longer required by the core Quartz code, but has been left to maintain backward compatibility.
#817

SchedName added to queries as sql paramter

---

src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs
src/Quartz.Tests.Integration/Impl/AdoJobStore/Common/DbMetadataTest.cs
src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj
src/Quartz/Impl/AdoJobStore/Common/dbproviders.netstandard.properties
src/Quartz/Impl/AdoJobStore/Common/dbproviders.properties

#768
I wasn't sure if the existing library should be changed in-place (to give users good async behaviour by default) or if a new named provider should be added instead (less of a breaking change?).

Switch MySQL library to MySqlConnector

---

src/Quartz.Plugins.TimeZoneConverter/Plugin/TimeZoneConverter/TimeZoneConverterPlugin.cs
src/Quartz/Core/QuartzScheduler.cs

This fixes issue #831 with System.TimeZoneNotFoundException thrown even when Quartz.Plugins.TimeZoneConverter is used.

Set TimeZoneUtil.CustomResolver in TimeZoneConverterPlugin.Initialize method

---

database/tables/tables_postgres.sql

for Postgres tables.
It's quite annoying to get errors about exceeding the limit when e.g. some job class name is very long.
I don't see any reason not to represent them as unlimited TEXT... this data type as been in Postgres since very old versions (7.1 from 2001 has it!) and [Postgres docs say "There is no performance difference"](https://www.postgresql.org/docs/10/datatype-character.html)

Use TEXT type instead of fixed-length VARCHAR

---

src/Quartz.Serialization.Json/Simpl/JsonObjectSerializer.cs

fixes #840
fixes #834
This fix instructs Newtonsoft to Serialize and Deserialize date objects as a DateTimeOffset. Because a DateTimeOffset can be cast in to a DateTime object, this fix shouldn't effect any DateTime serialization.
Here is an example that demonstrates the original issue: https://dotnetfiddle.net/5Q1gUZ

Fix Deserialization of DateTimeOffset when using JsonObjectSerializer

---

changelog.md
src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs

Reuse lock requestor id for subsequent calls in ExecuteInNonManagedTXLock

---

src/Quartz.AspNetCore/AspNetCore/HealthChecks/QuartzHealthCheck.cs
src/Quartz.AspNetCore/Quartz.AspNetCore.csproj
src/Quartz.AspNetCore/QuartzServiceCollectionExtensions.cs
src/Quartz.Extensions.DependencyInjection/Quartz.Extensions.DependencyInjection.csproj
src/Quartz.Extensions.Hosting/Quartz.Extensions.Hosting.csproj
src/Quartz.Server/Quartz.Server.csproj
src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj
src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj
src/Quartz/Quartz.csproj

As discussed in https://github.com/openiddict/openiddict-core/issues/361, this PR updates the various .csproj to use 2.1 as the minimum version for the .NET Platform Extensions, but without forcing a specific range to allow users to explicitly reference newer versions.
/cc @lahma

Use 2.1 as the minimum version for the .NET Platform Extensions

---

src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs

The `SimpleTypeLoadHelper` is used by default in the `StdSchedulerFactory` if no other `ITypeLoadHelper` is registered:
https://github.com/quartznet/quartznet/blob/9193fac3587b9a020bf861d2404d463d67e05b07/src/Quartz/Impl/StdSchedulerFactory.cs#L416
But if you don't explicitly call `UseSimpleTypeLoader()`, the required type isn't registered in DI and you get an `InvalidOperationException` on startup.
This changes registers the required service, as long as no other `ITypeLoadHelper` is added inside the call to `AddQuartz()`.
Unfortunately we can't call UseSimpleTypeLoader(), as that would overwrite the configuration for any other configured type loader (while leaving the service registration intact):
https://github.com/quartznet/quartznet/blob/89b414f142010086d057c70085d4fe3c65b39f26/src/Qua …

Register an ITypeLoadHelper by default in services.AddQuartz()

---

src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs

I am trying to integrate MassTransit with Quartz scheduler https://github.com/MassTransit/MassTransit/issues/2065
MassTransit integration breaks Quartz jobs replacing JobFactory with special one
For workaround i create new DI container, configure new ISchedulerFactory and pass it to MassTransit to not to affect old one for Quartz
Example:
```cs
var scheduler = new ServiceCollection()
// My common Quartz extension, uses .AddQuartz()
.AddQuartzExtension(
connectionStringBuilder,
environment,
configurator =>
{
// ...
})
// ILoggerFactory is required
.AddSingleton(context.GetRequiredService<ILoggerFactory>())
.BuildServiceProvider()
.GetRequiredService<ISchedulerFactory>();
```
If in new DI container is no `ILoggerFactory` quartz throws because of `.GetRequiredService`, next check for `!= …

Add clear exception message, remove not null check

---

changelog.md
src/Quartz/Xml/XMLSchedulingDataProcessor.cs

Changes the way how XMLSchedulingDataProcessor opens the XML file with job and trigger definitions to allow concurrent read-only access from other processes.
fixes #993

Allow concurrent access to XML file with job and trigger definitions

---

.gitignore
Quartz.sln
changelog.md
src/Quartz.Benchmark/JobDispatchBenchmark.cs
src/Quartz.Benchmark/Program.cs
src/Quartz.Benchmark/Quartz.Benchmark.csproj
src/Quartz.Examples/01_SimpleJobScheduler/HelloJob.cs
src/Quartz/Collections/EmptyEnumerator.cs
src/Quartz/Collections/EmptyReadOnlyCollection.cs
src/Quartz/Collections/HashHelpers.cs
src/Quartz/Collections/IDictionaryDebugView.cs
src/Quartz/Collections/OrderedDictionary.KeyCollection.cs
src/Quartz/Collections/OrderedDictionary.ValueCollection.cs
src/Quartz/Collections/OrderedDictionary.cs
src/Quartz/Collections/ReadOnlyCollectionWrapper.cs
src/Quartz/Collections/ThrowHelper.cs
src/Quartz/Core/JobRunShell.cs
src/Quartz/Core/ListenerManagerImpl.cs
src/Quartz/Core/QuartzScheduler.cs
src/Quartz/ExceptionHelper.cs
src/Quartz/Impl/JobExecutionContextImpl.cs
src/Quartz/JobDataMap.cs
src/Quartz/Simpl/PropertySettingJobFactory.cs
src/Quartz/TaskExtensions.cs
src/Quartz/Util/ObjectUtils.cs

Reduce memory usage and state machine creations.
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.508 (2004/?/20H1)
AMD Ryzen 7 2700X, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.100-rc.2.20479.15
[Host]     : .NET Core 3.1.9 (CoreCLR 4.700.20.47201, CoreFX 4.700.20.47203), X64 RyuJIT
DefaultJob : .NET Core 3.1.9 (CoreCLR 4.700.20.47201, CoreFX 4.700.20.47203), X64 RyuJIT
```
| Method |     Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |---------:|----------:|----------:|-------:|------:|------:|----------:|
|    Run | 5.736 μs | 0.0658 μs | 0.0615 μs | 0.9232 |     - |     - |   3.79 KB |
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.508 (2004/?/20H1)
AMD Ryzen 7 2700X, 1 CPU, 16 logical and 8 physical cores
.NET Core …
```

Optimize job dispatch performance

---

.editorconfig
Quartz.sln
build.fsx
src/Quartz.OpenTracing/Configuration/ServiceCollectionExtensions.cs
src/Quartz.OpenTracing/InstrumentationService.cs
src/Quartz.OpenTracing/Quartz.OpenTracing.csproj
src/Quartz.OpenTracing/QuartzDiagnostic.cs
src/Quartz.OpenTracing/QuartzDiagnosticOptions.cs

Hi everyone!
I was really happy about OpenTelemetry support but it's still in beta and most projects use OpenTracing instead.
I added OpenTracing support and it'd be great if you could help me to finish it correctly and publish this NuGet package.

Add Quartz.OpenTracing support 

---

src/Quartz/JobBuilder.cs

JobBuilder.UsingJobData(string key, string value) should be JobBuilder.UsingJobData(string key, string? value)
fixes #1025

JobBuilder.UsingJobData(string key, string value) should be JobBuilder.UsingJobData(string key, string? value)

---

src/Quartz/Util/StringKeyDirtyFlagMap.cs

* can handle DateTimeOffset (possible due Json serializer)
fixes #1027

Improve StringKeyDirtyFlagMap.GetDateTime

---

src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs

When the scheduler tries to recover all misfired triggers, if one of the triggers throws an exception due to some reason(Invalid CRON expression in my case), the remaining triggers are skipped due to the fact that the exception is not handled. So, we made this change to make the misfired trigger recovery process resilient to any kind if exception.

Handled exceptions thrown while retrieving the misfired trigger

---

docs/documentation/best-practices.md

There were a few unneeded commas, parentheses and a couple typos that were making this section a little difficult to read. 
I also wanted to add a little blurb about some of the symptoms that unhandled exceptions in jobs can lead to in order to make it easier for someone running into those kinds of issues to track down this specific section of documentation.

Clarifying some wording, fixing a couple typos in the Best Practices document

---

src/Quartz/Core/JobRunShell.cs

Updated JobRunShell to handle only scheduler-related cancellations.
Closes #1064

Updated JobRunShell to handle only scheduler-related cancellations

---

src/Quartz.Extensions.Hosting/QuartzHostedService.cs

Fix `NullReferenceException` in `QuartzHostedService.StopAsync` if
`StartAsync` has not been run.
`StartAsync` won't run if there's another hosted service that is registered
earlier and throws in its `StartAsync`. Exception in `StartAsync` causes
Asp.Net Core to begin shutdown during which all hosted services are stopped
via `StopAsync`.
#1123

Fix possible NRE in QuartzHostedService.StopAsync

---

src/Quartz/Xml/job_scheduling_data_2_0.xsd

Fix XSD schema to remove the dependency between `durable` and `recover` parameters according to the issue #1128

Fix XSD schema

---

docs/documentation/quartz-3.x/packages/hosted-services-integration.md
docs/documentation/quartz-3.x/packages/microsoft-di-integration.md
src/Quartz.Examples.AspNetCore/Startup.cs
src/Quartz.Examples.Worker/Program.cs
src/Quartz.Extensions.DependencyInjection/JobFactoryOptions.cs
src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
src/Quartz.Extensions.DependencyInjection/Simpl/JobActivatorCache.cs
src/Quartz.Extensions.DependencyInjection/Simpl/MicrosoftDependencyInjectionJobFactory.cs

This PR changes `MicrosoftDependencyInjectionJobFactory` to stop resolving jobs from the container and instead creates them with `ActivatorUtilities` (i.e. job dependencies are resolved from the container, the job is newed up).
Job types should no longer be registered in the container. `ScheduleJob` extension is changed to no longer register the job type.
This change fixes double disposal of `IDisposable` jobs (#1120). Prior to this change, `IDisposable` jobs were disposed twice: by the container as well as by the job factory (`ScopedJob`). And when there was no scope (`CreateScope=false`), the container kept all job instances until the container itself was disposed, creating a resource leak.
`AllowDefaultConstructor` option is now redundant and has been removed.
Fixes #1120

Use ActivatorUtilities in MicrosoftDependencyInjectionJobFactory

---

src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs

This removes redundant DI job registration which was missed in #1127 .

Remove redundant DI job registration from AddJob

---

src/Quartz.Examples.Worker/Program.cs
src/Quartz.Extensions.Hosting/QuartzHostedService.cs
src/Quartz.Extensions.Hosting/QuartzHostedServiceOptions.cs

Hi, this PR adds support for the already existing `ISchedulerFactory.StartDelayed` when using pre-prepared `AddQuartzHostedService`.

Add support for the ISchedulerFactory.StartDelayed in the QuartzHostedService

---

docs/documentation/quartz-3.x/tutorial/job-stores.md
src/Quartz/Impl/AdoJobStore/Common/dbproviders.netstandard.properties

Added the ability to optionally use `System.Data.SqlClient` on .NET Core (https://github.com/quartznet/quartznet/discussions/950#discussioncomment-415731)
If we want to use `System.Data.SqlServer` in .NET Core we can specify it explicitly with this parameter
`quartz.dataSource.myDS.provider = SystemDataSqlClient`

Restore System.Data.SqlClient support on .NET Core

---

src/Quartz/Impl/StdSchedulerFactory.cs

Use InstantiateType that can be overloaded to allow custom instantiation of plugins, job listeners and trigger listeners. When used with Quartz.AspNetCore, it will allow to use dependency injection in plugins and other types.

Use custom InstantiateType for all instantiations in StdSchedulerFactory

---

src/Quartz.Extensions.DependencyInjection/Simpl/MicrosoftDependencyInjectionJobFactory.cs

This PR aims to enable a configuration point to the private `IServiceScope` created by the `MicrosoftDependencyInjectionJobFactory`
With that solution in place we could inherit the `MicrosoftDependencyInjectionJobFactory` and configure scoped types based on Job Data or another property from the ambient context.

Added a configuration point to the private Scope of MicrosoftDependencyInjectionJobFactory

---

src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
src/Quartz.Tests.Unit/Extensions/DependencyInjection/ServiceCollectionExtensionsTests.cs
src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj
src/Quartz/JobBuilder.cs

Implements https://github.com/quartznet/quartznet/issues/1211.
`ScheduleJob(trigger => trigger.WithIdentity(...))`, without a job configurator, now sets the job identity to match the trigger's (instead of `"DEFAULT-[UUID]"`).

ScheduleJob(trigger => trigger.WithIdentity()): Set job identity to match

---

src/Quartz.Tests.Unit/SchedulerBuilderTest.cs
src/Quartz/SchedulerBuilder.cs

feat(ado-provider-extensions): add helper methods to setup Microsoft.Data.Sqlite

---

src/Quartz.Tests.Unit/JobDetailTest.cs
src/Quartz/Util/ObjectExtensions.cs

fix for job type loading after version change (#1283)

---

src/Quartz.Extensions.Hosting/QuartzHostedService.cs
src/Quartz.Tests.Unit/Core/QuartzSchedulerTest.cs
src/Quartz/Core/QuartzScheduler.cs

QuartzScheduler.StartDelay is changed not to wait on the background Task anymore.  Returning a task is preserved so that the API does not change.
Update TestStartDelayed test to take less time. This test is more non-deterministic now.
Fixes #1313

Fix StartDelay delaying the start of other hosted services

---

src/Quartz.Benchmark/QuartSchedulerBenchmark.cs
src/Quartz.Benchmark/SchedulerBenchmark.cs
src/Quartz/Core/QuartzScheduler.cs

Reduce allocations when notifying job listeners by avoiding captures.
**QuartSchedulerBenchmark**
|                                         Method | Branch |    Mean |   Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------------------------- |--------|--------:|--------:|--------:|-------:|------:|------:|----------:|
|  NotifyJobListenersToBeExecuted_SingleThreaded | v4     |334.3 ns | 0.65 ns | 0.58 ns | 0.0648 |     - |     - |     272 B |
|  NotifyJobListenersToBeExecuted_SingleThreaded | PR     |307.9 ns | 0.77 ns | 0.72 ns | 0.0305 |     - |     - |     128 B |
|   NotifyJobListenersToBeExecuted_MultiThreaded | v4     |475.5 ns | 0.77 ns | 0.68 ns | 0.0650 |     - |     - |     272 B |
|   NotifyJobListenersToBeExecuted_MultiThreaded | PR     |391.5 …

Reduce allocations when notifying job listeners.

---

src/Quartz.Benchmark/JobRunShellBenchmark.cs
src/Quartz/Core/JobRunShell.cs

Reduce allocations in JobRunShell by avoiding captures, and reduce interface calls.
Baby steps ...
<details>
|                                                      Method | Branch |    Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------------------------------------------ |--------|--------:|----------:|----------:|-------:|------:|------:|----------:|
| Success_NoTriggerListenersAndSingleJobListener_MayFireAgain | main   |1.627 us | 0.0043 us | 0.0035 us | 0.2747 |     - |     - |   1.13 KB |
| Success_NoTriggerListenersAndSingleJobListener_MayFireAgain | PR     |1.607 us | 0.0048 us | 0.0042 us | 0.2575 |     - |     - |   1.05 KB |
</details>

Reduce allocations and interface calls in JobRunShell

---

src/Quartz.Benchmark/QuartSchedulerBenchmark.cs
src/Quartz.Benchmark/RAMJobStoreBenchmark.cs
src/Quartz/Core/QuartzScheduler.cs

Remove allocations from captures when notifying trigger listeners.
Document **ConcurrentDictionary\<TKey,TValue>** 'trick' to check if dictionary is empty.
Add more scenarios to **QuartSchedulerBenchmark**.
<details>
|                                                     Method | Branch |    Mean |   Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------------------------------------------------- |--------|--------:|--------:|--------:|-------:|------:|------:|----------:|
| NotifyTriggerListenersFired_QuartScheduler1_SingleThreaded | main   |145.2 ns | 0.24 ns | 0.20 ns | 0.0439 |     - |     - |     184 B |
| NotifyTriggerListenersFired_QuartScheduler1_SingleThreaded | PR     |124.7 ns | 0.35 ns | 0.33 ns | 0.0324 |     - |     - | …

Remove allocations from captures when notifying trigger listeners

---

src/Quartz.Benchmark/RAMJobStoreBenchmark.cs
src/Quartz/Simpl/RAMJobStore.cs
src/Quartz/Util/SortedSetExtensions.cs

* Document default value of **MisfireThreshold**, and exception that is thrown.
* Avoid extra indirection in `GetFiredTriggerRecordId()` as `Convert.ToString(long, IFormatProvider)` in turn calls `long.ToString(IFormatProvider)` anyway.
* Update `GetTriggerKeysInternal(...)` to immediately initialize 'outList' as that is what we end up doing anyway.
* In `ApplyMisfire(TriggerWrapper tw)`, use `AddTicks(...)` instead of `AddMilliseconds(...)` to compute 'misfireTime' as a micro-optimization.
* Apply optimizations In AcquireNext(...):
* Use **SortedSet\<T>.Min** to get first item instead of using our extension method.
* No need to check return value of `timeTriggers.Remove(...)` as we just obtained the trigger from that list, and this while holding the instance-level lock.
* Avoid interface …

RAMJobStore: improve performance and reduce allocations

---

changelog.md
src/Quartz.Benchmark/SimpleTriggerImplBenchmark.cs
src/Quartz/Impl/Triggers/SimpleTriggerImpl.cs

Improve performance of **SimpleTriggerImpl** by:
* avoiding to repeatedly invoke virtual properties.
* using `Nullable<T>.GetValueOrDefault()` when we already verified that we have a value.
* simplifying conditions of while loops, and avoid entering while loops if possible.
* avoiding unnecessary calls to `SystemTime.UtcNow`.
* avoiding to compute the number of times fired for **RescheduleNowWithRemainingRepeatCount** when **RepeatCount** is **zero** or **RepeatIndefinitely**.
The improvement is bigger on .NET Framework than on .NET (Core).
**Important:**
The **endUtc** argument of `GetFireTimeBefore(...)` is no longer nullable. When we invoke this method, we always have a value for this argument. Let me know if you want me to revert that change.
<details>
<summary>Benchmark …

Improve performance of SimpleTriggerImpl

---

src/Quartz/Simpl/RAMJobStore.cs

Do not allocate a **List\<IOperableTrigger>** when no time triggers are available.
Remove unnessary null checks, and remove unnecessary lock.

RAMJobStore: Remove allocation and simplify

---

src/Quartz/Core/QuartzSchedulerThread.cs

When we acquired zero triggers, we calculate a randomized wait time.
For some reason we were:
1. getting the current time.
1. calculating the randomized wait time.
1. adding that randomized wait time to the time we obtained in **1**.
1. subtracting the time we obtained in **1** from the result of **3**.
This actually gives us the randomized wait time that we calculated in **2**, so we now use that directly.

Simplity calculation of 'timeUntilContinue'

---

src/Quartz.Plugins/Plugin/Xml/XMLSchedulingDataProcessorPlugin.cs
src/Quartz.Tests.Integration/ExceptionPolicy/ExceptionJobTest.cs
src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs
src/Quartz.Tests.Integration/Impl/SmokeTestPerformer.cs
src/Quartz.Tests.Unit/Core/QuartzSchedulerTest.cs
src/Quartz.Tests.Unit/Simpl/RAMJobStoreTest.cs
src/Quartz.Tests.Unit/TestUtil.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Jobs.cs

We should give preference to using **JobBuilder** to create a **IJobDetail** instance over directly initializing a **JobDetailImpl**.

Use JobBuilder to create IJobDetail instances

---

src/Quartz.Examples/Program.cs
src/Quartz.Serialization.Json/Converters/StringKeyDirtyFlagMapConverter.cs
src/Quartz.Tests.Integration/TestAssemblySetup.cs
src/Quartz.Tests.Integration/Xml/XMLSchedulingDataProcessorTest.cs
src/Quartz.Tests.Unit/Core/QuartzSchedulerTest.cs
src/Quartz.Tests.Unit/QualityTest.cs
src/Quartz.Tests.Unit/SerializationTestSupport.cs
src/Quartz.Tests.Unit/TestAssemblySetup.cs
src/Quartz/Core/QuartzScheduler.cs
src/Quartz/Impl/JobDetailImpl.cs
src/Quartz/Simpl/PropertySettingJobFactory.cs
src/Quartz/Util/ObjectExtensions.cs
src/Quartz/Util/ObjectUtils.cs
src/Quartz/Util/PropertiesParser.cs

Remove use of `Type.GetTypeInfo()` that dates back to early days of .NET Core.

Remove use of GetTypeInfo()

---

changelog.md
src/Quartz/Impl/Matchers/StringOperator.cs

Allow Equals(StringOperator?) to be overridden as it's a best practice to either override Equals(object?), Equals(T?) and GetHashCode(), or none of them.
I have a follow-up PR that adds (just) about full test coverage of **StringOperator**.

StringOperator: Allow Equals(StringOperator?) to be overridden

---

src/Quartz/Simpl/RAMJobStore.cs

Update **RAMJobStore** to use `StringOperator.Equals(StringOperator?)` instead of using `StringOperator.Equals(object?)`.

RAMJobStore: Use StringOperator.Equals(StringOperator?) instead of using Equals(object?)

---

src/Quartz.Tests.Unit/Impl/Matchers/StringOperatorTest.cs
src/Quartz/Impl/Matchers/StringOperator.cs

Update the **Equality** operator to return **true** in `Evaluate(string value, string compareTo)` when both **value** and **compareTo** are **null**. Previously, a **NullReferenceException** would be thrown.
For all other built-in operators, `Evaluate(string value, string compareTo)` now returns **false** instead of throwing a **NullReferenceException** or **ArgumentNullException** when **value** or **compareTo** (or both) are **null**.
Added unit tests.

StringOperator: improve dealing with null values

---

src/Quartz.Benchmark/DefaultThreadPoolBenchmark.cs
src/Quartz/Simpl/TaskSchedulingThreadPool.cs

Improve performance, reduce allocations and reduce contention of **TaskSchedulingThreadPool** by:
* Setting continuation on the wrapper task insteaad of the unwrapped task.
* Using a **CountDownEvent** instead of a **List\<Task>** to keep track of the (number of) running tasks and wait until all tasks have completed.
* Caching the delegate that we use to mark the task complete.
The biggest impact on allocations and certainly contention/locking comes from the usage of **CountDownEvent**.
<details>
|                                                           Method | Branch |    Mean  |    Error |   StdDev |  Gen 0 |  Gen 1 |  Gen 2 | Allocated |
|----------------------------------------------------------------- …

Improve performance, reduce allocations and reduce contention in TaskSchedulingThreadPool 

---

src/Quartz.Benchmark/JobExecutionContextImplBenchmark.cs
src/Quartz/Impl/JobExecutionContextImpl.cs

Lazy initialize cancellationTokenSource, cancellationToken, data and jobDataMap.
This has quite a positive impact on both performance and memory allocations.
**To be discussed:**
* Does this lazy init have to be threadsafe?
If it is, we'll need to introduce a lock field.
* Is it correct to lazy init **jobDataMap**?
I think it's not, because I assume we want the "state" of both the job and trigger data at the time we create the **JobExecutionContextImpl**.
<details>
|                                                       Method | Branch |    Mean |     Error |    StdDev |  Gen 0 |  Gen 1 |  Gen 2 | Allocated |
|------------------------------------------------------------- |-------:|--------:|----------:|----------:|-------:|-------:|-------:|----------:| …

Lazy initialize some properties of JobExecutionContextImpl

---

src/Quartz.Tests.Unit/Utils/DirtyFlagMapTest.cs
src/Quartz/Util/DirtyFlagMap.cs

Update `DirtyFlagMap.Put(TKey key, TValue val)`to only set the dirty flaw when we know that we managed to add or update an entry in the underlying dictionary.
Fixes first part of issue 14 in #1417

DirtyFlagMap: Update Put(TKey key, TValue val) to only set dirty flag if successful

---

changelog.md
src/Quartz.Benchmark/JobRunShellBenchmark.cs
src/Quartz.Benchmark/QuartSchedulerBenchmark.cs
src/Quartz.Benchmark/SchedulerBenchmark.cs
src/Quartz.Tests.Unit/Core/QuartzSchedulerResourcesTest.cs
src/Quartz.Tests.Unit/Core/QuartzSchedulerThreadTest.cs
src/Quartz.Tests.Unit/Impl/DirectSchedulerFactoryTest.cs
src/Quartz/Core/QuartzScheduler.cs
src/Quartz/Core/QuartzSchedulerResources.cs
src/Quartz/Core/QuartzSchedulerThread.cs
src/Quartz/ExceptionHelper.cs
src/Quartz/Impl/DirectSchedulerFactory.cs
src/Quartz/Impl/StdSchedulerFactory.cs

We now verify whether valid values are specified for **IdleWaitTime**, **MaxBatchSize** and **BatchTimeoutWindow**, and no longer replace **TimeSpan.Zero** with a default of **30 seconds** if explicitly set.
This last modification is to allow for scenarios where someone wants a very low latency and precise scheduler.
We should not implicitly / silently change the configuration specified by a user.
<details>
<summary>Detailed changes</summary>
&nbsp;
**StdSchedulerFactory**
* Use default value of **30 seconds** for idle wait time if not explicitly set
* No longer reject value greater than **zero** and less than **1000 milliseconds** for idle wait time.
**DirectSchedulerFactory**
* Throw **ArgumentOutOfRangeException** if **idleWaitTime** is less than **TimeSpan.Zero**, **maxBatchSize** is …

Verify scheduler configudation values, validate IdleWaitTime

---

src/Quartz.Tests.Unit/DailyTimeIntervalScheduleBuilderTest.cs
src/Quartz.Tests.Unit/DisallowConcurrentJobExecutionTest.cs
src/Quartz.Tests.Unit/JobExecutionAttributesInterfaceInheritanceTest.cs
src/Quartz.Tests.Unit/SchedulerTest.cs

Attempt to stabilize more tests:
* `Quartz.Tests.Unit.DailyTimeIntervalScheduleBuilderTest.TestScheduleInMiddleOfDailyInterval()`: provide more meaningful information when asserts fail.
* `Quartz.Tests.Unit.JobExecutionAttributesInterfaceInheritanceTest.TestNoConcurrentExecOnSameJob()`: add a small tolerance as **DateTime.(Utc)Now** does not have a high precision.
* `Quartz.Tests.Unit.DisallowConcurrentExecutionJobTest.TestNoConcurrentExecOnSameJob()`: add a small tolerance as **DateTime.(Utc)Now** does not have a high precision.
* `Quartz.Tests.Unit.SchedulerTest.ReschedulingTriggerShouldKeepOriginalNextFireTime()`: Ensure trigger does not immediately fire. Enable test on Linux.
Re-enable shutdown test in **Quartz.Tests.Unit.SchedulerTest**, and add test to verify that we do not wait for …

Stabilize tests

---

docs/documentation/quartz-3.x/tutorial/more-about-jobs.md

[...] than -> then only one instance of "SalesReportForJoe" can execute at a given time.

Fix typo in "More About Jobs & Job Details"

---

src/Quartz/Simpl/TriggerWrapperComparator.cs

Removes unnecessary null check from `TriggerWrapperComparator.GetHashCode()` as the **ttc** field is readonly and always initialized.

Remove unnecessary null check from TriggerWrapperComparator.GetHashCode()

---

src/Quartz.Tests.Unit/Impl/Triggers/DailyTimeIntervalTriggerImplTest.cs

Fix assertions to compare against LocalTime to avoid error when run in positive UTC timezone environment.
When The Unit tests were run in UTC+10 timezone they would fail due to the comparison being off by one in UTC compare.

Fix assertions to compare against LocalTime

---

src/Quartz/Impl/JobDetailImpl.cs
src/Quartz/JobBuilder.cs

Allow **PersistJobDataAfterExecution** and **ConcurrentExecutionDisallowed** to be explicitly set when building a IJobDetail.
When not set, we continue to use reflection to determine the values for these properties based on the presence (or absence) of **PersistJobDataAfterExecutionAttribute** and **DisallowConcurrentExecutionAttribute**.
If the job type is specified when the **JobDetailImpl** is constructed (using **JobBuilder**), then determining the value for these properties has now become a one-time cost.
Until this PR we payed for this each time these properties are accessed.
In case of **ConcurrentExecutionDisallowed** this is when:
* the trigger is acquired
* the trigger is fired
* the trigger(ed job) has completed
The creation and caching of **JobTypeInformation** for a given job …

JobBuilder: Allow PersistJobDataAfterExecution and ConcurrentExecutionDisallowed to be set

---

src/Quartz/Xml/XMLSchedulingDataProcessor.cs

I had the following problem with the replacement of an existing CronTrigger in a PersistentJobStorage: I configured the Trigger to run a Job in an Asp.Net Core app every night at 1 am using PersistentJobStore. Unfortunately my app was always down at 1 am. I configured the following:
```
options.Scheduling.ScheduleTriggerRelativeToReplacedTrigger = true;
options.Scheduling.OverWriteExistingData = true;
```
When my application started again in the morning it updated the trigger and set the trigger's NextFireTime to 1 am in the next night which caused that my trigger was not executed. I figured out that this problem only occurs when the trigger never had been executed before and it's PreviousFireTime is null.
When "ScheduleTriggerRelativeToReplacedTrigger" is enabled the NextFireTime of the …

Set NextFireTime of the replaced trigger relative to the old trigger's StartTime if the old trigger's PreviousFireTime is null

---

changelog.md
src/Directory.Build.props
src/Quartz.Examples/Quartz.Examples.csproj
src/Quartz.Jobs/Quartz.Jobs.csproj
src/Quartz.Plugins.TimeZoneConverter/Quartz.Plugins.TimeZoneConverter.csproj
src/Quartz.Plugins/Quartz.Plugins.csproj
src/Quartz.Serialization.Json/Quartz.Serialization.Json.csproj
src/Quartz.Server/Quartz.Server.csproj
src/Quartz/Quartz.csproj

- NET Framework 4.6.1 marked End Of Support in April2022 by Microsoft. 
#1549

task: Set minimum .NET Framework to 4.6.2 (#1549)

---

src/Quartz.Examples.AspNetCore/SecondSampleJobListener.cs
src/Quartz.Examples.AspNetCore/SecondSampleTriggerListener.cs
src/Quartz.Examples.AspNetCore/Startup.cs
src/Quartz.Extensions.DependencyInjection/ServiceCollectionSchedulerFactory.cs

Quartz will resolve job and trigger listeners from service provider only if there exists listener configuration class also in the service provider. This is added when IServiceCollectionQuartzConfigurator's add-methods are called. These add methods does not provide all the same overloads as service collection to add listeners and thus limits the possible ways to register listeners.
This PR changes the way Quartz resolves job and trigger listeners from service provider. All the listeners that are added to service collection will be used. If no configuration class is found, defaults are used.

Use job and trigger listeners without configurations

---

src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs

Ensure Scheduler is removed in teardown, change assertion to match test intent for test JobTypeNotFoundShouldNotBlock.
Closes #1563

fix (IntegrationTest): Ensure Scheduler removed in teardown, change test assertion

---

src/Quartz.Extensions.DependencyInjection/Simpl/MicrosoftDependencyInjectionJobFactory.cs
src/Quartz/IJobWrapper.cs
src/Quartz/Impl/JobExecutionContextImpl.cs

Allows to access the `InnerJob` of a `MicrosoftDependencyInjectionJobFactory#ScopedJob`. 
See discussion at https://github.com/quartznet/quartznet/discussions/1578/

Create IJobWrapper interface and let ScopedJob implement it

---

src/Quartz/IJobConfigurator.cs
src/Quartz/Impl/JobDetailImpl.cs
src/Quartz/JobBuilder.cs

Cherry picked commits for exposing DisallowConcurrentExecution and PersistJobDataAfterExecution in IJobConfigurator, and dependent changes made to the JobBuilder and JobDetailImpl.
I see there is some changes to setters, from public to private, which might qualify as a breaking change in 3.x. In that case I will walk those changes back in a new commit to avoid breaking.

Allow PersistJobDataAfterExecution and ConcurrentExecutionDisallowed to be explicitly in JobBuilder and pulled up to IJobConfigurator

---

changelog.md
src/Quartz.Benchmark/JobRunShellBenchmark.cs
src/Quartz.Benchmark/QuartSchedulerBenchmark.cs
src/Quartz.Benchmark/SchedulerBenchmark.cs
src/Quartz.Tests.Unit/Core/ListenerManagerTest .cs
src/Quartz.Tests.Unit/Core/QuartzSchedulerTest.cs
src/Quartz/Collections/OrderedDictionary.ValueCollection.cs
src/Quartz/Core/ListenerManagerImpl.cs
src/Quartz/Core/QuartzScheduler.cs
src/Quartz/IListenerManager.cs

This is a draft PR that mostly aims to gather feedback on the changes that I applied as I'm sure some (most? :p) of these changes will probably be considered controversial.
There are two parts to this PR:
* Optimize the job listener part of ListenerManagerImpl.
* Optimize the job listener part of QuartzScheduler.
**ListenerManagerImpl**
Optimize the way we deal with job listeners by:
* eliminating locking in GetJobListenerMatchers when no matchers were were added.
* eliminating locking in GetJobListeners when no job listeners were added.
* lazily initializing globalJobListeners and globalJobListenersMatchers dictionaries.
* not adding a EverythingMatcher for a job listener when no matchers were specified.
<details>
| …

Optimize notify of job listeners

---

src/Quartz.Benchmark/Directory.Build.props
src/Quartz.Tests.Unit/Collections/OrderedDictionaryTest.cs

If I do not set **ProduceReferenceAssembly** to **false**, I get the following error when I attempt to run our benchmarks against .NET 6.0:
> CSC : error CS0006: Metadata file 'C:\development\quartznet\src\Quartz.Benchmark\bin\Release\net6.0\ref\Quartz.Benchmark.dll' could not be found [C:\development\quartznet\src\Quartz.Benchmark\bin\release\net6.0\eabb1d91-56a8-446e-b662-2e305185d641\BenchmarkDotNet.Autogenerated.csproj]
Build FAILED.
> CSC : error CS0006: Metadata file 'C:\development\quartznet\src\Quartz.Benchmark\bin\Release\net6.0\ref\Quartz.Benchmark.dll' could not be found [C:\development\quartznet\src\Quartz.Benchmark\bin\release\net6.0\eabb1d91-56a8-446e-b662-2e305185d641\BenchmarkDotNet.Autogenerated.csproj]
I also added a test that I forgot to commit in my previous PR.

Allow benchmarks to run against .NET 6.0

---

src/Quartz/JobDataMap.cs
src/Quartz/Util/StringKeyDirtyFlagMap.cs

Added `TryGet` versions for `GetXxx`, `GetXxxValueFromString`, and `GetXxxValue` methods.
*   I was tempted to refactor many of the existing `GetXxx` and `GetXxxValue` methods, because most of each group follows the same pattern. I left them alone for now, and I similarly used a repetitive pattern for the new methods instead of refactoring.
*   Two of the types don't have the standard complement of three methods. I assumed there was a reason for this and did not add missing methods.
*   `char` has `GetCharFromString` (only method named `GetXxxFromString`) and `GetChar`, but it does not have `GetCharValueFromString` or `GetCharValue`
*   `Guid?` does not have `GetNullableGuidFromString`
*   There were no unit tests for the existing methods, so I did not add any for the new ones.
*   I'm …

Add TryGet functions to JobDataMap and StringKeyDirtyFlagMap

---

docs/documentation/quartz-3.x/tutorial/job-stores.md

The path in the section about the ADO storage is not correct. This fixes it.

Fix pathname in job-stores documentation.

---

src/Quartz.Tests.Integration/AdoSchedulerTest.cs
src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs
src/Quartz.Tests.Integration/Impl/AdoJobStore/Common/DbMetadataTest.cs
src/Quartz.Tests.Integration/Impl/AdoJobStore/DeleteNonExistsJobTest.cs
src/Quartz.Tests.Integration/JobDataMapStorageTest.cs
src/Quartz.Tests.Integration/RAMJobStoreTest.cs
src/Quartz.Tests.Integration/Xml/XMLSchedulingDataProcessorTest.cs

Set test `[category]` against database integration tests, enabling easier exclusion per db in development.
Existing category `sqlserver` was prefixed with `db-` 
For example, https://www.jetbrains.com/help/resharper/Test_Categories.html#ignore

Set test [category] for vendor database integration tests

---

src/Quartz.Tests.Integration/JobMaintenanceTests.cs
src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj
src/Quartz.Tests.Integration/RAMJobStoreTest.cs
src/Quartz.Tests.Integration/TestHelpers/SchedulerHelper.cs
src/Quartz.Tests.Unit/Impl/JobType/JobTypeTests.cs
src/Quartz.Tests.Unit/JobBuilderTest.cs
src/Quartz.Tests.Unit/JobDetailTest.cs
src/Quartz/IJobDetail.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Jobs.cs
src/Quartz/Impl/JobDetailImpl.cs
src/Quartz/Impl/JobType.cs
src/Quartz/JobBuilder.cs
src/Quartz/JobDataMap.cs
src/Quartz/Util/ObjectExtensions.cs

Reduce the need to construct the stored job `Type` , allowing maintenance tasks such as `UnschduleJob` to operate when the stored job Type can no longer be constructed.
JobTypeSerialized is stored and can be retrieved as Type still via a Lazy getter
It should be a `Non-breaking change`, but if external code depended on exceptions being thrown for invalid job type retrieval this might introduce unexpected results
Should resolve #1560  - (V4) Error in JobDetailImpl due to null JobType being passed
fixes #1560

Serialized field for Job Type to enable maintenance on Jobs that cannot be constructed to their Type

---

changelog.md
docs/documentation/quartz-4.x/configuration/reference.md
src/Quartz.Tests.Unit/SchedulerBuilderTest.cs
src/Quartz/Impl/StdSchedulerFactory.cs
src/Quartz/SchedulerBuilder.cs

Use configuration value `quartz.jobStore.dbRetryInterval` instead of deprecated `quartz.scheduler.dbFailureRetryInterval`, which is not used to set the property  of `DbRetryInterval` in JobStoreSupport
Resolves #1623

fix: (Config) Use configuration value quartz.jobStore.dbRetryInterval to set DbRetryInterval

---

src/Quartz.Extensions.DependencyInjection/ServiceCollectionSchedulerFactory.cs
src/Quartz/Impl/StdSchedulerFactory.cs

fixes #1587
I moved the call to SchedulerRepository.Bind to GetScheduler, as this makes the registration process clearer.
You can't write tests against this as it would pollute the SchedulerRepository singleton as noted in #1453.

Make StdSchedulerFactory and ServiceCollectionSchedulerFactories threadsafe

---

changelog.md
src/Quartz.Extensions.DependencyInjection/QuartzOptions.cs
src/Quartz.Extensions.DependencyInjection/ServiceCollectionSchedulerFactory.cs

So this seems to be never-ending battle against the Options binder. Now they expect that if you implement `IDictionary<,>`, the type must be of type (or inherit from) `Dictionary<,>`. Changing `QuartzOptions` to inherit from `Dictionary<string, string?>` instead of `NameValueCollection `seems to resolve the problem.
Slightly API-breaking but said to be in progress...
fixes #1748

Change QuartzOptions to inherit from Dictionary<string, string?>

---

src/Quartz/Core/QuartzScheduler.cs

Minor performance improvement and reduced allocations in case global job listeners are registered.
**Before:**
|                                                        Method |     Mean |   Error |  StdDev |  Gen 0 | Allocated |
|-------------------------------------------------------------- |---------:|--------:|--------:|-------:|----------:|
| NotifyJobListenersToBeExecuted_QuartScheduler1_SingleThreaded | 102.1 ns | 0.21 ns | 0.18 ns | 0.0114 |      48 B |
| NotifyJobListenersToBeExecuted_QuartzScheduler1_MultiThreaded | 144.5 ns | 1.58 ns | 1.40 ns | 0.0114 |      48 B |
| NotifyJobListenersToBeExecuted_QuartScheduler2_SingleThreaded | 356.3 ns | 2.32 ns | 1.94 ns | 0.0267 |     112 B |
| NotifyJobListenersToBeExecuted_QuartzScheduler2_MultiThreaded | 313.9 ns | 1.84 ns | 1.63 ns | …

Use concrete array to enumerate job listeners

---

src/Quartz.Examples.HttpClient/Program.cs
src/Quartz.Examples.HttpClient/Quartz.Examples.HttpClient.csproj
src/Quartz.HttpClient/HttpClient/HttpClientExtensions.cs
src/Quartz.HttpClient/HttpClientOptions.cs
src/Quartz.HttpClient/QuartzHttpClientServiceCollectionExtensions.cs
src/Quartz.HttpClient/Simpl/HttpSchedulerProxyFactory.cs
src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs
src/Quartz/Impl/DirectSchedulerFactory.cs
src/Quartz/Impl/RemoteScheduler.cs
src/Quartz/Impl/StdSchedulerFactory.cs
src/Quartz/SPI/IRemotableSchedulerProxyFactory.cs
src/Quartz/SchedulerBuilder.cs
src/Quartz/Simpl/RemotingSchedulerExporter.cs
src/Quartz/Simpl/RemotingSchedulerProxyFactory.cs

This PR adds support for creating `HttpScheduler` using `StdSchedulerFactory`.
I changed the `IRemotableSchedulerProxyFactory` to return `IScheduler` instead of `IRemotableQuartzScheduler` and implemented `HttpSchedulerProxyFactory` which creates `HttpScheduler`. If the default implementation is used through `StdSchedulerFactory`, only base address can be configured for the `HttpClient`. However, one can inherit their own implementation from `HttpSchedulerProxyFactory` which can configure the `HttpClient`. I added examples for both of these cases into `Quartz.Examples.HttpClient`.
I also added extension methods to register `HttpScheduler` into service collection. As it is registered as `IScheduler`, only single scheduler can be added this way. There is also example about this in …

Add support for creating HttpScheduler with StdSchedulerFactory

---

src/Quartz.HttpClient/QuartzHttpClientServiceCollectionExtensions.cs

`AddQuartzHttpClient` method did not pass the JsonSerializerOptions given by user to the created `HttpScheduler`.

AddQuartzHttpClient should use given JsonSerializerOptions

---

src/Quartz.Examples.HttpClient/Program.cs
src/Quartz.HttpClient/Quartz.HttpClient.csproj
src/Quartz.HttpClient/QuartzHttpClientServiceCollectionExtensions.cs
src/Quartz.HttpClient/Simpl/SchedulerTypeBuilder.cs
src/Quartz.Tests.Unit/Extensions/DependencyInjection/QuartzHttpClientServiceCollectionExtensionsTest.cs
src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj
src/Quartz.Tests.Unit/Simpl/SchedulerTypeBuilderTest.cs
src/Quartz/Impl/DelegatingScheduler.cs

Current implementation of `services.AddQuartzHttpClient()` will register the `HttpScheduler` as `IScheduler` and thus only single client can be added.
This PR adds support for using marker interfaces to register multiple `HttpScheduler`s by using `services.AddQuartzHttpClient<IMyScheduler>()`. Quartz will dynamically create implementation for the given interface and register it into the service collection. The code to generate the dynamic types is based on code from MassTransit.
I tested the implementation only by using the tests and examples included in this PR. So, there might be some corner cases where the current implementation will not work, but we can fix those as they come up.

Add support for registering multiple HttpSchedulers

---

docs/documentation/quartz-3.x/how-tos/job-template.md

Noticed the typo + the prefix of the class.
C# standard typically uses `A` prefix for abstract classes and I think as a standard (based on other jobs created) `SampleJob` is a cleaner name.

Cleanup JobTemplate docs

---

src/Quartz.Extensions.DependencyInjection/IServiceCollectionQuartzConfigurator.cs
src/Quartz.Extensions.DependencyInjection/ServiceCollectionQuartzConfigurator.cs

Resolves issue #1852 
Adds the following overloads;
```csharp
void AddSchedulerListener<T>(T implementationInstance) where T : class, ISchedulerListener;
void AddSchedulerListener<T>(Func<IServiceProvider, T> implementationFactory) where T : class, ISchedulerListener;
void AddJobListener<T>(T implementationInstance, params IMatcher<JobKey>[] matchers) where T : class, IJobListener;
void AddJobListener<T>(Func<IServiceProvider, T> implementationFactory, params IMatcher<JobKey>[] matchers) where T : class, IJobListener;
void AddTriggerListener<T>(T implementationInstance, params IMatcher<TriggerKey>[] matchers) where T : class, ITriggerListener;
void AddTriggerListener<T>(Func<IServiceProvider, T> implementationFactory, params IMatcher<TriggerKey>[] matchers) where T : class, …
```

[DependencyInjection]: Add new listener overloads

---

changelog.md
src/Quartz.AspNetCore/Quartz.AspNetCore.csproj
src/Quartz.Extensions.DependencyInjection/Quartz.Extensions.DependencyInjection.csproj
src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
src/Quartz.Extensions.Hosting/Quartz.Extensions.Hosting.csproj
src/Quartz.Extensions.Hosting/QuartzHostedService.cs
src/Quartz.Tests.Unit/QuartzHostedServiceTests.cs

* use 2.1 packages for netstandard2.0
* use 3.1.0 packages for netcoreapp3.1
* use 6.0.0 packages for net6.0
fixes #1593

Add explicit netcoreapp3.1 and net6.0 targets to MS integration projects

---

src/Quartz/Collections/HashHelpers.cs

I found this unused internal function and have put up a PR to remove it. It doesn't appear to be used in the containing assembly or the assemblies referenced via `InternalsVisibleTo`. I don't know the history of it but I'm guessing it may've been from a previous resizing strategy.

Remove unused `HashHelpers.PowerOf2` function

---

src/Quartz.Tests.Unit/Impl/AdoJobStore/StdAdoDelegateTest.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Jobs.cs
src/Quartz/JobKey.cs
src/Quartz/Util/Key.cs

Here's the [discussion](https://github.com/quartznet/quartznet/discussions/1921). This is a PR for `3.x`-branch.
> one option is to add `internal` setter for the property
I've managed without adding new setters and just use existing internal ctor which suits me just well.

Add missing "disallow concurrency" materialization for jobs

---

src/Quartz.Tests.Unit/Simpl/TaskSchedulingThreadPoolTest.cs
src/Quartz/Simpl/TaskSchedulingThreadPool.cs

Ensure continuation applies to the underlying task.
Fixes #1933.

TaskSchedulingThreadPool: Ensure continuation applies to the underlying task

---

src/Quartz.Tests.Unit/Core/QuartzRandomTest.cs
src/Quartz/Core/QuartzRandom.cs

An integer overflow is possible in the `Next(int minValue, int maxValue)` if the difference between those two values is greater than 2^31. It doesn't looks like this can happen in the library itself since all usages have hard-coded safe values, but since the class is public it's possible someone else may hit this.
I've also added a few other tests to validate the happy path of this function

Fix integer overflow in `QuartzRandom.Next(int, int)`

---

.gitignore
src/Quartz.AspNetCore/AspNetCore/QuartzServiceCollectionExtensions.cs
src/Quartz.Examples.AspNetCore/Startup.cs

fixes #1948
namespace changed to `Quartz.AspNetCore`

Change QuartzServiceCollectionExtensions namespace to Quartz.AspNetCore in Quartz.AspNetCore project

---

src/Quartz.Tests.Unit/CronExpressionTest.cs
src/Quartz/CronExpression.cs

Fix to detect invalid cron expression character trailing a '?'  (resolves #1953)

Detect invalid CRON expression character trailing a '?'

---

src/Quartz.Extensions.DependencyInjection/ServiceCollectionSchedulerFactory.cs

Step to reproduce:
1. .Net Framework 4.8 project
2. Libraries:
* Microsoft.Extensions.DependencyInjection
* Quartz.net 3.6.0
* Quartz.Extensions.DependencyInjection 3.6.0
3. Configuration in app.config
Exception
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Quartz.Impl.StdSchedulerFactory.GetNamedConnectionString(String dsConnectionStringName)
at Quartz.Impl.StdSchedulerFactory.<Instantiate>d__65.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Quartz.Impl.StdSchedulerFactory.<GetScheduler>d__71.MoveNext()
— End of stack trace from previous …
```

ServiceCollectionSchedulerFactory.GetNamedConnectionString passes wrong value to base

---

src/Directory.Build.props
src/Directory.Packages.props
src/Quartz/Impl/AdoJobStore/CalendarIntervalTriggerPersistenceDelegate.cs
src/Quartz/Impl/AdoJobStore/DailyTimeIntervalTriggerPersistenceDelegate.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs
src/Quartz/Impl/SchedulerRepository.cs
src/Quartz/Impl/StdSchedulerFactory.cs
src/Quartz/SchedulerBuilder.cs
src/Quartz/Simpl/SimpleTypeLoadHelper.cs
src/Quartz/Util/DirtyFlagMap.cs
src/Quartz/Xml/XMLSchedulingDataProcessor.cs

Ubuntu Build is generating warnings for NU1505.
```
Error: /home/runner/work/quartznet/quartznet/src/Quartz.Extensions.DependencyInjection/Quartz.Extensions.DependencyInjection.csproj : error NU1505: Warning As Error: Duplicate 'PackageDownload' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageDownload' items are: Microsoft.NETCore.App.Ref [5.0.0], Microsoft.NETCore.App.Ref [6.0.14]. [TargetFramework=net6.0]
00:38:03 [ERR] /home/runner/work/quartznet/quartznet/src/Quartz.Extensions.DependencyInjection/Quartz.Extensions.DependencyInjection.csproj : error NU1505: Warning As Error: Duplicate 'PackageDownload' items found. Remove the duplicate items or use the Update functionality to ensure a consistent …
```

Fix build on Linux

---

Quartz.sln.DotSettings
changelog.md
docs/documentation/quartz-4.x/tutorial/crontrigger.md
docs/documentation/quartz-4.x/tutorial/crontriggers.md
src/Quartz.Tests.Unit/CronExpressionTest.cs
src/Quartz/CronExpression.cs
src/Quartz/Util/SerializationInfoExtensions.cs

- Add cron parser support for `'L'` and `'LW'` in expression combinations daysOfMonth (#1939) (#1288)
- There is a limit of only one 'L' in the expression.  ie 
`"0 15 10 7,15,L,L-2 * ?"` will fail  but 
`"0 15 10 7,15,L-2 * ? "` will pass.

Cron support for 'L' and 'LW' in expression daysOfMonth

---

database/tables/tables_postgres.sql

Postgres fencing DROP TABLES statements with `client_min_messages = WARNING`
Reset to NOTICE after done.
Logs for integration tests are showing warnings for DROP TABLES when they really aren't, adding to noise.

Reduce the C/I warning display for postgres

---

src/Quartz/Logging/IJobDiagnosticData.cs
src/Quartz/Logging/JobDiagnosticData.cs
src/Quartz/Logging/JobDiagnosticsWriter.cs

Extend object passed to DiagnosticListener.Start/EndActivity.
Fix for #1966

Extend object passed to DiagnosticListener.Start/EndActivity

---

Quartz.sln.DotSettings
src/Quartz.Tests.Unit/CronExpressionTest.cs
src/Quartz/CronExpression.cs
src/Quartz/CronExpressionConstants.cs
src/Quartz/CronExpressionSummary.cs

- Add guard for invalid `L` token location.
- Add guard for `DayOfWeek` on `L` token being out of range
- Add guards for `nthDayOfWeek` being out of range
- Increase test coverage on CronExpression class
- (CronExpression) Extract CronExpressionSummary & CronExpressionConstants.
- (CronExpression) `StoreExpressionVals` refactored 
- (CronExpression) Remove `GetDaysOfMonth`, was refactored out into other methods and is unused.
- (CronExpression) `CheckNext` return values are unused, changed to return void
- CronExpression.GetExpressionSummary() emits `\r\n` for newlines via AppendLine, previously was `\n`  ( I doubt this would cause any concern)

Refactor CronExpression, add guards for invalid usage, add tests

---

changelog.md
src/Quartz.Tests.Unit/CronExpressionTest.cs
src/Quartz/CronExpression.cs

When deserializing a CronExpression outside of builtin Quartz Serializers (for example to store in a custom store). Then calling `GetNextValidTimeAfter` will throw a NullReferenceException
This is due to `BuildExpression` not being called
Resolves #1996

Fix for deserializing CronExpression using Json Serializer throwing exception on GetNextValidTimeAfter

---

changelog.md
docs/documentation/quartz-4.x/tutorial/crontrigger.md
src/Quartz.Tests.Unit/CronExpressionTest.cs
src/Quartz/CronExpression.cs

- Ability to specify an offset from the last weekday of the month  resolves #1287
For Example `LW-2`
- If final day value will cross month boundary, ie LW-30 in February would result in possible -2 day. The value for day will reset to 1.  This was preferred over throwing an exception at runtime 
~~NOTE: PR Branch is built on top of #1972~~
EDIT: Rebased on main

Ability to specify an offset from the last weekday of the month (#1287)

---

src/Quartz.Plugins/Plugin/Interrupt/JobInterruptMonitorPlugin.cs

**Change:**
Reading MaxRuntime from the MergedDataMap instead of JobDataMap.
This allows to set the MaxRunTime also in the trigger configuration. Before this change only configure a 'gracefully' interrupt in JobDetails was possible.
**Reason for change:**
I have the situation to have several (long running) jobs that start at different times with same parameters and need to be finished 'gracefully'  after a different time
This would also work with multiple jobs with one trigger each, but made the configuration bigger.

JobInterruptMonitor Plugin: Read MaxRunTime from MergedJobDataMap

---

.editorconfig
Quartz.sln.DotSettings
changelog.md
docs/documentation/quartz-4.x/tutorial/crontrigger.md
docs/documentation/quartz-4.x/tutorial/crontriggers.md
src/Quartz.Tests.Unit/CronExpressionTest.cs
src/Quartz/CronExpression.cs

- CronExpression support DayOfMonth and DayOfWeek together (inclusive values)
resolves #1543
Outdated tests removed, condition no longer valid.
```text
public void TestFormatExceptionWildCardDayOfMonthAndDayOfWeek()
public void TestFormatExceptionSpecifiedDayOfMonthAndWildCardDayOfWeek()
public void TestFormatExceptionWildCardDayOfMonthAndSpecifiedDayOfWeek()
```
Below changes were reverted for performance reasons
~~`monthMap` and `dayMap` changed to `IReadOnlyDictionary`~~
~~protected fields initialised instead of null~~
~~Branched from #1972 - https://github.com/jafin/quartznet/tree/refactor-cron-expressions~~
EDIT: Rebased on main

Add CRON support for DayOfWeek and DayOfMonth to be set together (inclusive rules)

---

src/Quartz.Benchmark/CronExpressionBenchmark.cs
src/Quartz/CronExpression.cs

Micro performance optimization in CronExpression
**4.x with this change:**
|            Method |     Mean |    Error |   StdDev |   Gen0 | Allocated |
|------------------ |---------:|---------:|---------:|-------:|----------:|
| CreateExpressions | 35.96 us | 0.505 us | 0.518 us | 3.4180 |  55.93 KB |
4.x before change:  0c9ba23189c85223917d1ecbebbf2a951b891044
|            Method |     Mean |    Error |   StdDev |   Gen0 | Allocated |
|------------------ |---------:|---------:|---------:|-------:|----------:|
| CreateExpressions | 50.90 us | 0.981 us | 1.008 us | 5.0049 |  82.08 KB |
3.x 9d136a8d26122f0ff087f7ff67705673c1742ce8
|            Method |     Mean |    Error |   StdDev |   Gen0 | Allocated |
|------------------ |---------:|---------:|---------:|-------:|----------:|
| …

Optimize CronExpression and small reduction on allocation

---

src/Quartz.Benchmark/CronExpressionBenchmark.cs
src/Quartz.Tests.Unit/CronExpressionTest.cs
src/Quartz.Tests.Unit/CronFieldTest.cs
src/Quartz/CronExpression.cs
src/Quartz/CronExpressionConstants.cs
src/Quartz/CronExpressionSummary.cs
src/Quartz/Util/SortedSetExtensions.cs

* don't store individual values when AllSpec in use
* remove AllSpecInt and NoSpecInt
| **Diff**|Method|Mean|Error|Allocated|
|------- |-------|-------:|-------|-------:|
| Old |CreateExpressionsAndCalculateFireTimeAfter|17.58 μs|0.223 μs|18.75 KB|
| **New** |	| **5.769 μs (-67%)** | **0.0163 μs** | **4.73 KB (-75%)** |
| Old |CreateExpressionsAndCalculateFireTimeAfter|16.37 μs|0.099 μs|17.51 KB|
| **New** |	| **5.519 μs (-66%)** | **0.0603 μs** | **5.45 KB (-69%)** |
| Old |CreateExpressionsAndCalculateFireTimeAfter|16.88 μs|0.107 μs|18.7 KB|
| **New** |	| **6.242 μs (-63%)** | **0.0120 μs** | **4.45 KB (-76%)** |
| Old |CreateExpressionsAndCalculateFireTimeAfter|17.97 μs|0.312 μs|20.28 KB|
| **New** |	| **6.054 μs (-66%)** | **0.0081 μs** | **3.24 KB (-84%)** |
| Old …

Replace SortedSet.TailSet with separate CronField container

---

build/Build.cs

Fix issue introduced in #2044 with Nuke Pack not working.
- CopyFileToDirectory must be rooted

fix(build): Nuke Pack for 7.0.2

---

src/Quartz.Tests.Integration/RAMJobStoreTest.cs
src/Quartz.Tests.Unit/Impl/AdoJobStore/UpdateTriggerTest.cs
src/Quartz/Impl/AdoJobStore/StdAdoConstants.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Triggers.cs

This is the fix from #2039 backported to the 3.x branch. Please see the other PR for details.

Fix persistence of extended properties when the trigger type is changed (v3)

---

src/Quartz.Tests.Integration/RAMJobStoreTest.cs
src/Quartz.Tests.Unit/Impl/AdoJobStore/UpdateTriggerTest.cs
src/Quartz/Impl/AdoJobStore/StdAdoConstants.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Triggers.cs

When using JobStoreTX (ADO.NET), changing the type of a trigger (by calling `ScheduleJob` with `replace` set to `true`) will corrupt the trigger state in the database. The extended properties relating to the old state will be left unchanged. Extended properties relating to the new type will not be written to the database. Once the next fire time for the updated trigger is reached, the trigger will fail to be loaded from the database and the scheduler will stop executing _all_ jobs.
This is an issue with version 3.6.2 and the latest code in the main branch.
RAMJobStore works correctly.
Here's an example that will reproduce the problem:
```c#
public class Test
{
public static async Task Execute()
{
var factory = new StdSchedulerFactory();
var scheduler = await factory.GetScheduler();
await …
```

Fix persistence of extended properties when the trigger type is changed

---

src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Calendars.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Jobs.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Triggers.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs

Backport of #2060 to version 3.x
Fixes #2054
Use `CommandBehavior.SequentialAccess` to work around performance issues with SqlClient when reading blobs (SQL Server specific), and remove unnecessary copying to `MemoryStream` (All ADO.NET delegates).

[3.x] Optimize reading blobs on SQL Server

---

src/Quartz.Tests.Unit/Impl/AdoJobStore/StdAdoDelegateTest.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Calendars.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Jobs.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Triggers.cs
src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs

Fixes #2054
Use `CommandBehavior.SequentialAccess` to work around performance issues with SqlClient when reading blobs (SQL Server specific), and remove unnecessary copying to `MemoryStream` (All ADO.NET delegates).

Optimize reading blobs on SQL Server

---

docs/documentation/quartz-3.x/tutorial/crontrigger.md

The documentation specifies `**` to be separated by a space.
They may have appeared due to the linker trying to display Italic.

Add missing spaces to Examples

---

changelog.md
src/Quartz.Jobs/Job/SendMailJob.cs
src/Quartz.Plugins/Plugin/Interrupt/JobInterruptMonitorPlugin.cs
src/Quartz.Tests.Unit/JobDataMapTest.cs
src/Quartz.Tests.Unit/Plugin/Interrupt/AutoInterruptableJobTest.cs
src/Quartz/Util/StringKeyDirtyFlagMap.cs

When a Key in JobDataMap does not exist/or is null, `TryGetXXXValue` will return false.
Presently, it will return true, due to `Convert.ToInt(null)`  (and other types) returning 0
The follow changes were also done, to adapt to this change:
+ Add `TryGetString` to match other method.
+ Refactor `JobInterruptMonitor` and `SendMailJob` to change to use Try methods now that Gets may throw `KeyNotFoundException`.
+ add a release note for change

Fix for JobDataMap, TryGetValue return false when key is null/doesn't exist

---

src/Quartz.Jobs/Job/SendMailJob.cs
src/Quartz.Tests.Unit/Job/SendMailJobTest.cs

When a `SendMailJob` fails to construct message from missing parameters, it should throw a `JobExecutionException`.
Branched from #2125

SendMailJob to throw JobExecutionException on BuildMessage construction failure due to missing mandatory params.

---

src/Quartz.Tests.Unit/Impl/StdSchedulerFactoryTest.cs
src/Quartz/Impl/StdSchedulerFactory.cs

Fixes #2212 by omitting environment variable "quartz.config" (`StdSchedulerFactory.PropertiesFile`) from the list of environment variable containing possible quartz props which get added by `StdSchedulerFactory.OverrideWithSysProps`

Fix handling of env var quartz.config (#2212)

---

src/Quartz.Tests.Unit/Utils/TimeZoneUtilTest.cs
src/Quartz/Impl/Calendar/HolidayCalendar.cs

Fix issue with Holiday Calendar not identifying a date included due to checking modified DateOnly value with base
Resulting in an exception from hitting year 9999.
- Changed to compare original date value with base Calendars, and date only value with current calendar validator (not base calendars). 
- Add scenario described in #2270 
Naming is hard, not sure `IsTimeIncludedThisCalendar` is a good name
I did not check other day calendar types, perhaps the scenario exists in other calendars in similar configuration

Fix issue with Holiday Calendar with nested calendars not identifying NextIncludedTime

---

src/Quartz.Tests.Unit/Impl/Calendar/DailyCalendarTest.cs
src/Quartz.Tests.Unit/Impl/Calendar/NestedCalendarTests.cs
src/Quartz/Impl/Calendar/DailyCalendar.cs

Improve performance of `DailyCalendar` solving `GetNextIncludedTimeUtc` by changing the stepping increment based on the Start/End range of the DailyCalendar parameters.
In the original issue OP noted this took >13 seconds.
With a similar test, it is now milliseconds.
fixes #2270

Improve performance of DailyCalendar solving GetNextIncludedTimeUtc  #2270

---

Analyzers/BannedSymbols.txt
Directory.Packages.props
Quartz.sln
src/Quartz/Configuration/ServiceCollectionExtensions.cs
src/Quartz/CronExpression.cs
src/Quartz/CronExpressionConstants.cs
src/Quartz/DateBuilder.cs
src/Quartz/Impl/Calendar/AnnualCalendar.cs
src/Quartz/Impl/Triggers/CalendarIntervalTriggerImpl.cs
src/Quartz/Impl/Triggers/CronTriggerImpl.cs
src/Quartz/Impl/Triggers/DailyTimeIntervalTriggerImpl.cs
src/Quartz/Quartz.csproj
src/Quartz/SystemTime.cs
src/Quartz/TriggerConstants.cs
src/Quartz/Util/TimeZoneUtil.cs
src/Quartz/Xml/XMLSchedulingDataProcessor.cs

Replace DateTime usage with TimeProvider.System
Replace implicit DateTime to DateTimeOffset conversions with explicit. Add in Analyzer to ensure DateTime isn't used.
Remove a check for IsRUnningOnMono. As it is no longer one of the supported deployment frameworks. Registers a TimeProvider in DI (but is not using it)
`Bcl.TimeProvider` supports Net8, net 4.6.2 ; Netstandard 2.0
❌ This does NOT implement DI for TimeProvider.  A few usage of DateTime are in static variables and private constructors.  I believe this would possibly need a servicelocator to pull in as a dependency.  And would rather see the DI work handle this if possible.
Relates to #2079

Refactor code to use TimeProvider.System

---

changelog.md
src/Quartz.Tests.Unit/Utils/TimeZoneUtilTest.cs
src/Quartz/Impl/Calendar/HolidayCalendar.cs

Fix Holiday Calendar with Nested Calendars sometimes crashing when resolving NextIncludedTime
Picked from main.
Resolves #2270

Fix Holiday Calendar with Nested Calendars sometimes crashing when resolving NextIncludedTime

---

src/Quartz.Web/App/webpack.config.js

Supply default value for `reduce` to please Sonarlint.

Fix lint warning about missing initial value in array.reduce in webpack.config.js Quartz.Web

---

docs/documentation/quartz-3.x/packages/aspnet-core-integration.md

Fixed typo in aspnet-core-integration.md by changing "listers" to "listeners"

fix typo in aspnet-core-integration.md

---

src/Quartz.Tests.Unit/Impl/Calendar/DailyCalendarTest.cs
src/Quartz/Impl/Calendar/DailyCalendar.cs

- Simplify GetStartOfDay
- Ensure GetEndOfDay has maximum precision of platform
**Describe the bug**
I am seeing test `TestTimeZone2` introduced in #2113 failing.
**Version used**
Quartz.NET 3.9.0
**To Reproduce**
Have a negative timezone offset on your system clock. 
Run unit tests.
**Expected behavior**
Passing test.
**Additional context**
Looking at the test line where the failure occurs:
https://github.com/quartznet/quartznet/blob/e62b215388d4bba29d0c027c8249bafc6a2b6605/src/Quartz.Tests.Unit/Impl/Calendar/DailyCalendarTest.cs#L128
A negative `timeZoneOffset.Hours` is subtracted from 24 resulting in a time range greater than 24 hours which is more than the available hours in the day.
Adding a negative solves this issue for me. I believe this was the intent.

Support negative timezone offsets in TestTimeZone2

---

src/Quartz.Benchmark/DefaultThreadPoolBenchmark.cs
src/Quartz.Benchmark/SchedulerBenchmark.cs
src/Quartz.Examples/09_TriggeringAJobUsingJobListeners/SimpleJob1Listener.cs
src/Quartz.HttpClient/HttpClient/HttpScheduler.cs
src/Quartz.Plugins/Plugin/Interrupt/JobInterruptMonitorPlugin.cs
src/Quartz.Plugins/Plugin/Xml/XMLSchedulingDataProcessorPlugin.cs
src/Quartz.Server/Program.cs
src/Quartz.Server/QuartzServer.cs
src/Quartz.Tests.Integration/Impl/AdoJobStore/DeleteNonExistsJobTest.cs
src/Quartz.Tests.Unit/DisallowConcurrentJobExecutionTest.cs
src/Quartz.Tests.Unit/Impl/DirectSchedulerFactoryTest.cs
src/Quartz.Tests.Unit/JobExecutionAttributesInterfaceInheritanceTest.cs
src/Quartz.Tests.Unit/Plugin/History/LoggingJobHistoryPluginTest.cs
src/Quartz.Tests.Unit/QuartzHostedServiceTests.cs
src/Quartz.Tests.Unit/SchedulerTest.cs
src/Quartz/Hosting/QuartzHostedService.cs

These are the lines that were identified as Safe cleanup actions in my other PR.
- Do not sync wait on ValueTask, always call ToTask first.
- ContinueWith on TaskScheduler.Default instead of current

Use async pattern where already available.

---

docs/.vuepress/configs/sidebar/en.ts

Fix documentation link to Db Page (currently 404)

Fix documentation link to Db page

---

src/Quartz/Impl/AdoJobStore/Common/DataSourceDbProvider.cs

My bad on this. I was testing out the change today and ran into an exception due to the existing ADO implementation assigning a connection & transaction to the command. This'll resolve that issue.

Fix DbDataSource connection creation

---

.github/workflows/docs.yml
.github/workflows/qodana_code_quality.yml

Update Build actions to use checkout/@v4 & cache/@v4

---

src/Quartz.Tests.Unit/CronExpressionTest.cs
src/Quartz.Tests.Unit/Impl/Calendar/CronCalendarTest.cs
src/Quartz/CronExpression.cs
src/Quartz/TriggerConstants.cs
src/Quartz/Util/SortedSetExtensions.cs

Fix an issue whereby setting a monthly `CronExpression` with flag `weekdayonly`  `W` , 
when the scheduled day falls on a weekend (Sun/Sat), 
Quartz would incorrectly skip ahead to the next month (or non weekend date month when calling `GetTimeAfter`
Full detail in #2331 
- Targets v4
Incorporate test and fix from #2330 by @Skimmenthal13 (credit PR #2490) relating to NextFireTime bug when next month is shorter and using `W` modifier at end of month with greater days than next month

Fix CronExpression not always returning correct next schedule for weekdayonly and month flags.  Relates to #2331

---

docs/documentation/quartz-1.x/tutorial/job-stores.md
docs/documentation/quartz-2.x/tutorial/job-stores.md
docs/documentation/quartz-3.x/tutorial/job-stores.md
docs/documentation/quartz-4.x/tutorial/job-stores.md

Fixes:
- spacing after period of previous sentence 
- superfluous t in preposition.

fix(docs): typos in job-stores section in tutorials

---

src/Quartz.Tests.Unit/Utils/DirtyFlagMapTest.cs
src/Quartz/Util/DirtyFlagMap.cs

To allow use of `System.Collections.Generic.CollectionExtensions.GetValueOrDefault` extensions, the `DirtyFlagMap` class needed to implement `IReadOnlyDictionary<TKey, TValue?>`, as the .NET Framework assumes (but does not enforce) every `IDictionary<>` also implementing the `IReadOnlyDictionary<>` interface, in the same way that `Dictionary<>` does.
These changes allow the use of `GetValueOrDefault` for `SchedulerContext` and `JobDataMap` to replace the need for 
```
string item = null;
var value = dirtyFlagMap.TryGetValue(key, out item) ? item : null;
```
with
```
var value = dirtyFlagMap.GetValueOrDefault(key)
```
(Note: There's a bunch of auto-formatting applied by Visual Studio that I can try to strip out if you feel it's necessary)

Implemented the IReadOnlyDictionary<TKey, TValue?> interface in DirtyFlagMap

---

src/Quartz/Util/DirtyFlagMap.cs

Turns out MaybeNull is an output attribute, and it results in the compiler assuming an object is no longer guaranteed non-null after being added.
The actual input attribute is AllowNull.
- AllowNullAttribute: Specifies that null is allowed as an input even if the corresponding type disallows it.
- MaybeNullAttribute: Specifies that an output may be null even if the corresponding type disallows it.

DirtyFlagMap-fixAdd
