quartznet/quartznet

src/Quartz/Impl/AdoJobStore/JobStoreTX.cs, src/Quartz/Impl/Calendar/DailyCalendar.cs, src/Quartz/Impl/Triggers/CronTriggerImpl.cs
Fixed a couple of missing parameter tags and one invalid signature.
=> Fixed a few xmldoc issues

src/Quartz/Impl/AdoJobStore/Common/dbproviders.properties
add mysql 6.9.5 provider support
=> add mysql 6.9.5 provider support

src/Quartz/Core/QuartzScheduler.cs, src/Quartz/Core/QuartzSchedulerThread.cs, src/Quartz/DailyTimeIntervalScheduleBuilder.cs, src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs, src/Quartz/Impl/AdoJobStore/StdAdoConstants.cs, src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs, src/Quartz/Impl/Calendar/AnnualCalendar.cs, src/Quartz/Impl/Calendar/CronCalendar.cs, src/Quartz/Impl/Calendar/DailyCalendar.cs, src/Quartz/Impl/Calendar/HolidayCalendar.cs, src/Quartz/Impl/Calendar/MonthlyCalendar.cs, src/Quartz/Impl/Calendar/WeeklyCalendar.cs, src/Quartz/Impl/JobExecutionContextImpl.cs, src/Quartz/Impl/Triggers/CalendarIntervalTriggerImpl.cs, src/Quartz/Impl/Triggers/CronTriggerImpl.cs, src/Quartz/Impl/Triggers/SimpleTriggerImpl.cs, src/Quartz/Job/SendMailJob.cs, src/Quartz/JobExecutionException.cs, src/Quartz/Plugin/Xml/XMLSchedulingDataProcessorPlugin.cs, src/Quartz/Simpl/PropertySettingJobFactory.cs, src/Quartz/Simpl/RAMJobStore.cs, src/Quartz/Util/DirtyFlagMap.cs, src/Quartz/Xml/XMLSchedulingDataProcessor.cs
Fixed a few code redundancies reported by Resharper. Nothing major, just doing my bit with a little spring cleaning.
=> Remove various code redundancies

src/Quartz/Core/JobRunShell.cs
Heh, I got a bit bothered by that brace. Thought it was my code that did it :)
=> Remove lonely brace

src/Quartz/CronExpression.cs
This could happen when there isn't enough memory - OutOfMemoryException
=> Include inner exception

src/Quartz.Tests.Unit/Impl/DirectSchedulerFactoryTest.cs, src/Quartz/Impl/DirectSchedulerFactory.cs
=> Removed dbFailureRetryInterval since it is no longer used

src/Quartz/Impl/AdoJobStore/MySQLDelegate.cs, src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs
add limit for mysql (slow when has large misfire job)
=> add limit for mysql (slow when has large misfire job)

src/Quartz/Impl/StdSchedulerFactory.cs, src/Quartz/Simpl/SimpleThreadPool.cs, src/Quartz/Util/LogicalThreadContext.cs
Primarily subs in AsyncLocal for CallContext. A couple other minor bug fixes and comment changes, too.
=> Addressing a couple more 'todo's for the .NET Core port

src/Quartz.Tests.Integration/AdoSchedulerTest.cs, src/Quartz.Tests.Integration/Core/MissSchedulingChangeSignalTest.cs, src/Quartz.Tests.Integration/FailFastLoggerFactoryAdapter.cs, src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs, src/Quartz.Tests.Integration/Impl/AdoJobStore/DeleteNonExistsJobTest.cs, src/Quartz.Tests.Integration/RAMSchedulerTest.cs, src/Quartz.Tests.Unit/Core/MissSchedulingChangeSignalTest.cs, src/Quartz.Tests.Unit/PriorityTest.cs, src/Quartz/Impl/Matchers/StringOperator.cs, src/Quartz/Quartz.csproj, src/Quartz/Simpl/RAMJobStore.cs
A handful of test updates (and a couple small product fixes) to account for recent serialization and async changes.
=> Test updates

src/Quartz.Examples/App.config, src/Quartz.Examples/Quartz.Examples.csproj, src/Quartz.Examples/project.json, src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj, src/Quartz.Tests.Integration/app.config, src/Quartz.Tests.Integration/project.json, src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj, src/Quartz.Tests.Unit/app.config, src/Quartz.Tests.Unit/project.json, src/Quartz/Core/QuartzScheduler.cs, src/Quartz/Core/QuartzSchedulerResources.cs, src/Quartz/Core/QuartzSchedulerThread.cs, src/Quartz/Quartz.csproj, src/Quartz/SPI/IThreadPool.cs, src/Quartz/Simpl/ClrThreadPool.cs, src/Quartz/Util/AsyncManualResetEvent.cs, src/Quartz/Util/TaskUtil.cs, src/Quartz/project.json
* Switched to .NET 4.6.1 to have support for `TaskCreationOptions.RunContinuationsAsynchronously` (see bug in 4.6 https://github.com/dotnet/coreclr/issues/2021)
* Implemented `AsyncManualResetEvent` for pause support
* Introduced really dumb version `IJobWorkerPool`
=> [SPIKE] Task based API spike for job worker pool

src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs
Addresses an integration test failure
=> Small bug fix

src/Quartz/Impl/AdoJobStore/StdAdoConstants.cs
=> fix for select SqlSelectJobForTrigger

src/Quartz/Impl/AdoJobStore/StdAdoConstants.cs
now it's using primary key
same fix as to master 3.0 alpha
=> fix for select SqlSelectJobForTrigger to 2.x

src/Quartz/Simpl/RemotingSchedulerExporter.cs
=> Fix for issue #464 RemotingSchedulerExporter can't create remoting channel on Mono

src/Quartz/Core/QuartzSchedulerThread.cs
=> Implemented wait time between retries for AquireNextTriggers after fail

src/Quartz/Core/QuartzRandom.cs, src/Quartz/Core/QuartzScheduler.cs, src/Quartz/Core/QuartzSchedulerThread.cs
Implement Random number generator based on RNGCryptoServiceProvider which provides better randomness then System.Random.
=> Implement better random number generator

src/Quartz.Plugins/Plugin/Xml/XMLSchedulingDataProcessorPlugin.cs, src/Quartz/Core/QuartzScheduler.cs, src/Quartz/Core/QuartzSchedulerThread.cs, src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs, src/Quartz/Listener/BroadcastJobListener.cs, src/Quartz/Listener/BroadcastSchedulerListener.cs, src/Quartz/Listener/BroadcastTriggerListener.cs
Missing ConfigureAwait(false); See #618
=> Missing ConfigureAwait(false);

src/Quartz/Core/QuartzScheduler.cs
=> fixes #678 ISchedulerListener.JobScheduled not called when scheduling multiple jobs

src/Quartz.Jobs/Job/DirectoryScanJob.cs, src/Quartz.Jobs/Job/DirectoryScanJobModel.cs
Hi, I have added search patterns/sub directory search option to the Directory Scanner job.
Thanks and Regards,
Senthil
=> 411 - Added search patterns/sub directory search to directoty scanner job

src/Quartz/Simpl/RAMJobStore.cs
Eliminate extra lookup in `RAMJobStore.StoreJobInternal(IJobDetail new…Job, bool replaceExisting)` when **replaceExisting** is **true** and job exists.
Only create **JobWrapper** when job doesn't yet exist.
**Before:**
|                                      Method |       Mean |     Error |    StdDev |     Median | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|-------------------------------------------- |-----------:|----------:|----------:|-----------:|------------:|------------:|------------:|--------------------:|
|   StoreJob_ReplaceExisting_JobExists_Serial |   275.5 ns | 11.284 ns | 31.456 ns |   266.6 ns |      0.0658 |           - |           - |               104 B |
| StoreJob_ReplaceExisting_JobExists_Parallel |   657.8 ns |  3.677 ns |  3.439 ns |   657.7 …
=> Improve performance and reduce allocations of RAMJobStore.StoreJobInternal when job exists

src/Quartz/Core/ListenerManagerImpl.cs, src/Quartz/Impl/AdoJobStore/Common/DbProvider.cs, src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs, src/Quartz/Impl/JobExecutionContextImpl.cs, src/Quartz/Listener/JobChainingJobListener.cs, src/Quartz/Xml/XMLSchedulingDataProcessor.cs
=> Reduce virtual calls.

src/Quartz/Util/QueuedTaskScheduler.cs
Removes unused functionality from **QueuedTaskScheduler** hereby reducing complexity and improving performance.
=> Remove unused functionality from QueuedTaskScheduler

src/Quartz.Jobs/Job/DirectoryScanJob.cs, src/Quartz.Jobs/Job/DirectoryScanJobModel.cs, src/Quartz.Jobs/Job/IDirectoryScanListener.cs
Hi,
I have added the ability to detect the deleted files to dir scanner job. Added FilesDeleted method to the listener interface. I have implemented this by saving the current file list in the JobDataMap and comparing the list during the  next iteration. Please review and share your feedback - happy to implement any changes.
Thanks,
Senthil
=> fixes#411 - Added ability to detect deleted files and notify the listener

documentation/quartz-2.x/tutorial/more-about-jobs.md, documentation/quartz-3.x/tutorial/more-about-jobs.md
Small extension on what is currently in documentation about property injecting, to describe issue related to using property injection and a custom job factory.
=> Add line about property injecting

documentation/quartz-2.x/tutorial/more-about-jobs.md
=> Minor typo in Lesson 3 v2.x

documentation/quartz-3.x/tutorial/more-about-jobs.md
=> Fix typo in Lesson 3 v3.x

src/Quartz/JobDataMap.cs, src/Quartz/Util/StringKeyDirtyFlagMap.cs
Resolves: https://github.com/quartznet/quartznet/issues/837
This will need testing prior to release.
=> Add handling of Guid's in the JobDataMap

src/Quartz.AspNetCore/QuartzHostedService.cs, src/Quartz.AspNetCore/QuartzHostedServiceOptions.cs, src/Quartz.AspNetCore/QuartzServiceCollectionExtensions.cs, src/Quartz.Examples.AspNetCore/ExampleJob.cs, src/Quartz.Examples.AspNetCore/Quartz.Examples.AspNetCore.csproj, src/Quartz.Examples.AspNetCore/Startup.cs, src/Quartz.Examples.AspNetCore/quartz_jobs.config, src/Quartz.Examples/quartz_jobs.xml, src/Quartz.Extensions.DependencyInjection/IServiceCollectionQuartzConfigurator.cs, src/Quartz.Extensions.DependencyInjection/IServiceCollectionTriggerConfigurator.cs, src/Quartz.Extensions.DependencyInjection/JobFactoryOptions.cs, src/Quartz.Extensions.DependencyInjection/MicrosoftDependencyInjectionJobFactory.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionQuartzConfigurator.cs, src/Quartz.Extensions.DependencyInjection/TriggerExtensions.cs, src/Quartz.Plugins.TimeZoneConverter/TimeZonePluginConfigurationExtensions.cs, src/Quartz.Plugins/PluginConfigurationExtensions.cs, src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs, src/Quartz.Tests.Integration/RAMSchedulerTest.cs, src/Quartz.Tests.Unit/SchedulerBuilderTest.cs, src/Quartz/IPropertyConfigurer.cs, src/Quartz/PropertiesHolder.cs, src/Quartz/SchedulerBuilder.cs
* Use void methods and properties with option style configuration
* Make sure we can do XML configuration for DI too
=> Refine configuration

changelog.md, src/Quartz.Examples.AspNetCore/SampleJobListener.cs, src/Quartz.Examples.AspNetCore/SampleSchedulerListener.cs, src/Quartz.Examples.AspNetCore/SampleTriggerListener.cs, src/Quartz.Examples.AspNetCore/Startup.cs, src/Quartz.Examples.AspNetCore/appsettings.json, src/Quartz.Extensions.DependencyInjection/IServiceCollectionQuartzConfigurator.cs, src/Quartz.Extensions.DependencyInjection/Quartz.Extensions.DependencyInjection.csproj, src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionQuartzConfigurator.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionSchedulerFactory.cs
* add scheduler/job/trigger listeners to registration API
* read appsetting.json Quartz section
fixes #877
=> DI registration and configuration improvements

changelog.md, docker/firebird/Dockerfile, src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs, src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj, src/Quartz.Tests.Unit/Impl/AdoJobStore/StdAdoDelegateTest.cs, src/Quartz.Tests.Unit/Impl/AdoJobStore/UpdateTriggerTest.cs, src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj, src/Quartz/Impl/AdoJobStore/Common/dbproviders.netstandard.properties, src/Quartz/Impl/AdoJobStore/Common/dbproviders.properties, src/Quartz/Impl/AdoJobStore/JobStoreCMT.cs, src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs, src/Quartz/Quartz.csproj
=> Switch to Microsoft.Data.SqlClient

build.fsx, changelog.md
=> Ensure NuGet.exe is part of produced zip to ensure build works

src/Quartz/Core/JobRunShell.cs, src/Quartz/Simpl/SimpleJobFactory.cs
=> Add original exception message to created exception when job instantiation fails

changelog.md, src/Quartz.Tests.Unit/CalendarIntervalTriggerTest.cs, src/Quartz.Tests.Unit/CronScheduleBuilderTest.cs, src/Quartz.Tests.Unit/DailyTimeIntervalScheduleBuilderTest.cs, src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj, src/Quartz.Tests.Unit/SimpleScheduleBuilderTest.cs, src/Quartz/Impl/Triggers/CalendarIntervalTriggerImpl.cs, src/Quartz/Impl/Triggers/CronTriggerImpl.cs, src/Quartz/Impl/Triggers/DailyTimeIntervalTriggerImpl.cs, src/Quartz/Impl/Triggers/SimpleTriggerImpl.cs
=> Ensure GetScheduleBuilder for triggers respects IgnoreMisfirePolicy

changelog.md, src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj, src/Quartz.Tests.Integration/Xml/TestData/ComplexCron.xml, src/Quartz.Tests.Integration/Xml/XMLSchedulingDataProcessorTest.cs, src/Quartz.Tests.Unit/Plugin/Xml/XMLSchedulingDataProcessorPluginTest.cs, src/Quartz/Xml/XMLSchedulingDataProcessor.cs, src/Quartz/Xml/job_scheduling_data_2_0.xsd
=> Remove error-prone cron expression validation from XML schema

changelog.md, docs/documentation/quartz-3.x/tutorial/configuration-resource-usage-and-scheduler-factory.md, src/Quartz.AspNetCore/Quartz.AspNetCore.csproj, src/Quartz.Examples.AspNetCore/Quartz.Examples.AspNetCore.csproj, src/Quartz.Examples.AspNetCore/Startup.cs, src/Quartz.Extensions.DependencyInjection/IServiceCollectionQuartzConfigurator.cs, src/Quartz.Extensions.DependencyInjection/Quartz.Extensions.DependencyInjection.csproj, src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionQuartzConfigurator.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionSchedulerFactory.cs, src/Quartz.Server/Quartz.Server.csproj, src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj, src/Quartz/LogContext.cs, src/Quartz/Quartz.csproj, src/Quartz/Simpl/MicrosoftLoggingProvider.cs
=> Allow configuring Microsoft.Extensions.Logging.Abstractions

changelog.md, src/Quartz/Impl/DirectSchedulerFactory.cs
=> Properly assign MaxConcurrency in CreateVolatileScheduler

src/Quartz.Serialization.Json/Simpl/JsonObjectSerializer.cs
=> Throw meaningful exception when JsonObjectSerializer hasn't been initialized

changelog.md, src/Directory.Build.props, src/Quartz.Tests.Integration/Impl/AdoJobStore/JobStoreSupportTest.cs, src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj, src/Quartz.Tests.Unit/Impl/AdoJobStore/JobStoreSupportTest.cs, src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj, src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs, src/Quartz/Quartz.csproj
=> Remove dependency on Microsoft.Data.SqlClient

changelog.md, src/Quartz/CronExpression.cs
=> Revert "GetTimeBefore() and GetFinalFireTime() throw NotImplementedException

changelog.md, src/Quartz.Examples/Quartz.Examples.csproj, src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs, src/Quartz/Impl/AdoJobStore/Common/ConfigurationBasedDbMetadataFactory.cs, src/Quartz/Impl/AdoJobStore/Common/DbProvider.cs, src/Quartz/Impl/StdSchedulerFactory.cs
=> Parse DB metadata from quartz.config

changelog.md, src/Quartz.Plugins/Plugin/History/LoggingJobHistoryPlugin.cs, src/Quartz.Plugins/Plugin/History/LoggingTriggerHistoryPlugin.cs
=> Add default names for LoggingJobHistoryPlugin and LoggingTriggerHistoryPlugin

src/Quartz.Extensions.DependencyInjection/Simpl/MicrosoftDependencyInjectionJobFactory.cs
Fix https://github.com/quartznet/quartznet/issues/998
=> Resolve scoped jobs from scopes

docs/documentation/quartz-3.x/configuration/reference.md
Updated references from isClustered to clustered
=> Updated references from isClustered to clustered

changelog.md, src/Quartz.Plugins/Plugin/Xml/XMLSchedulingDataProcessorPlugin.cs, src/Quartz/Impl/StdSchedulerFactory.cs, src/Quartz/Util/FileUtil.cs, src/Quartz/Xml/XMLSchedulingDataProcessor.cs
=> Xamarin Android can return null for AppContext.BaseDirectory

changelog.md, src/Quartz/Impl/StdSchedulerFactory.cs
=> Should not set default job factory type

docs/documentation/quartz-2.x/tutorial/crontrigger.md
Year field of cron expression was in wrong cell
=> Fixed table layout issue in crontrigger.md

docs/documentation/quartz-3.x/configuration/reference.md
=> text update

src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs
When I want to dynicmic add a Job ,it ususally use the reflection.so  i add a regular AddJob method .
=> Add  a regular AddJob Type

src/Quartz/Impl/AdoJobStore/DBSemaphore.cs
Corrects the logging as mentioned in #1133
=> Logging with Stacktrace corrected

src/Quartz.Extensions.DependencyInjection/ITriggerConfigurator.cs, src/Quartz.Extensions.DependencyInjection/TriggerConfigurator.cs, src/Quartz/IJobConfigurator.cs, src/Quartz/JobBuilder.cs, src/Quartz/TriggerBuilder.cs
Resolves #1141 .
Added support for `GUID` and `char` in:
- `ITriggerConfigurator` (and it's implementation)
- `IJobConfigurator` (and it's implementation)
- `TriggerBuilder`
Let me know if I've missed anything!
Thanks.
=> Add GUID and char support to UsingJobData methods

changelog.md, src/Quartz.Examples.AspNetCore/Startup.cs, src/Quartz.Examples.Worker/Program.cs, src/Quartz.Extensions.DependencyInjection/JobFactoryOptions.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionQuartzConfigurator.cs, src/Quartz.Extensions.DependencyInjection/Simpl/JobActivatorCache.cs, src/Quartz.Extensions.DependencyInjection/Simpl/MicrosoftDependencyInjectionJobFactory.cs
=> Try resolving jobs from service provider before resorting to ActivatorUtilities

changelog.md, src/Quartz/Simpl/HostNameBasedIdGenerator.cs
=> Simplify DNS name resolution in HostNameBasedIdGenerator

src/Quartz/Core/JobRunShell.cs
=> JobRunShell handle Job CancellationToken

src/Quartz.Tests.Unit/CronTriggerTest.cs, src/Quartz/Impl/Triggers/CronTriggerImpl.cs
removed overwrite of test date so the offset is kept
#1187
=> make WillFireOn method of CronTriggerImpl to keep the offset of test date

src/Quartz/Impl/AdoJobStore/DBSemaphore.cs
Fixes the result of DbLock so that only the needed Releases are triggered.
Fixes #1236
=> fixes #1236 double release lock

docs/documentation/quartz-3.x/quick-start.md, docs/documentation/quartz-3.x/tutorial/using-quartz.md, src/Quartz.Examples.AspNetCore/Startup.cs, src/Quartz.Examples/12_RemoteClientServerJobScheduling/RemoteClientExample.cs, src/Quartz.Examples/12_RemoteClientServerJobScheduling/RemoteServerExample.cs, src/Quartz.Examples/13_ClusteringJobsExecution/ClusteringJobsExecutionExample.cs, src/Quartz.Examples/14_RunJobsByPriorityWithTriggersPriority/RunJobsByPriorityWithTriggersPriorityExample.cs, src/Quartz.Examples/15_ConfigureJobSchedulingByUsingXmlConfigurations/ConfigureJobSchedulingByUsingXmlConfigurationsExample.cs, src/Quartz.Extensions.DependencyInjection/IServiceCollectionQuartzConfigurator.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionQuartzConfigurator.cs, src/Quartz.Server/quartz.config, src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs, src/Quartz.Tests.Integration/Impl/RemoteSchedulerSmokeTest.cs, src/Quartz.Tests.Integration/Utils/ObjectExtensions.cs, src/Quartz.Tests.Unit/CronExpressionTest.cs, src/Quartz.Tests.Unit/Impl/StdSchedulerFactoryTest.cs, src/Quartz.Tests.Unit/InterrubtableJobTest.cs, src/Quartz.Tests.Unit/PriorityTest.cs, src/Quartz.Tests.Unit/SchedulerTest.cs, src/Quartz.Tests.Unit/TestRemoting.cs, src/Quartz/Core/JobRunShell.cs, src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Calendars.cs, src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Jobs.cs, src/Quartz/Impl/DirectSchedulerFactory.cs, src/Quartz/Logging/LogContext.cs, src/Quartz/SchedulerBuilder.cs, src/Quartz/SchedulerMetaData.cs, src/Quartz/Simpl/PropertySettingJobFactory.cs, src/Quartz/Simpl/TaskSchedulingThreadPool.cs
=> Tweak scheduler building API and remove reference to SimpleThreadPool

src/Quartz.Examples.AspNetCore/Startup.cs, src/Quartz.Extensions.DependencyInjection/IServiceCollectionQuartzConfigurator.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionQuartzConfigurator.cs, src/Quartz.Tests.Unit/SchedulerTest.cs, src/Quartz/SchedulerBuilder.cs
=> Expose more configuration options via programmatic APIs

Quartz.sln, docker/sqlserver-mot/Dockerfile, docker/sqlserver/Dockerfile, src/Quartz.Jobs/Job/SendMailJob.cs, src/Quartz.Plugins/Plugin/Management/ShutdownHookPlugin.cs, src/Quartz/Impl/AdoJobStore/AdoUtil.cs, src/Quartz/Impl/AdoJobStore/ClusterManager.cs, src/Quartz/Impl/AdoJobStore/ConnectionAndTransactionHolder.cs, src/Quartz/Impl/AdoJobStore/MisfireHandler.cs, src/Quartz/Impl/SchedulerDetailsSetter.cs, src/Quartz/Impl/StdSchedulerFactory.cs, src/Quartz/Impl/Triggers/CronTriggerImpl.cs, src/Quartz/Simpl/PropertySettingJobFactory.cs, src/Quartz/Simpl/SimpleJobFactory.cs, src/Quartz/Simpl/TaskSchedulingThreadPool.cs, src/Quartz/Util/Configuration.cs, src/Quartz/Util/DBConnectionManager.cs, src/Quartz/Util/FileUtil.cs, src/Quartz/Util/QuartzEnvironment.cs, src/Quartz/Util/TimeZoneUtil.cs
=> Replace static loggers with instance-based

src/Quartz.Extensions.DependencyInjection/ServiceCollectionSchedulerFactory.cs
=> Protect DI scheduler initialization from concurrent initialization

src/Quartz/Impl/Triggers/SimpleTriggerImpl.cs
I have some other (performance-related) changes coming up for **SimpleTriggerImpl**, but this file has a mixture of tabs and spaces for indentation.
I've now normalized it to use spaces.
=> Normalize indentation to spaces for SimpleTriggerImpl

src/Quartz.Tests.Unit/Impl/Triggers/SimpleTriggerImplTest.cs
Add unit tests for `SimpleTriggerImpl.GetFireTimeAfter(...)`.
=> Add unit tests for SimpleTriggerImpl.GetFireTimeAfter(...)

src/Quartz/Core/JobRunShell.cs
Avoids a few interface calls in **JobRunShell**.
=> Avoid a few interface calls in JobRunShell

src/Quartz.Tests.Unit/Utils/DirtyFlagMapTest.cs
=> Add unit tests for DirtyFlagMap

src/Quartz/CronExpression.cs, src/Quartz/Impl/JobDetailImpl.cs, src/Quartz/Impl/Triggers/AbstractTrigger.cs, src/Quartz/Util/DirtyFlagMap.cs
Do not catch exceptions that occur while cloning.
Fixes #1415.
=> Let exceptions bubble up that occur while cloning

src/Quartz.Benchmark/JobExecutionContextImplBenchmark.cs, src/Quartz.Benchmark/SchedulerBenchmark.cs
Improvements to scheduler benchmarks in order to get more accurate results.
=> General improvements to scheduler benchmarks.

docs/documentation/faq.md
=> Fix typo in FAQ / performance of AdoJobStore

docs/documentation/quartz-3.x/tutorial/more-about-jobs.md
Name property same as JobData key "myFloatValue" used in previous samples to make "injection" work.
=> Rename FloatValue into MyFloatValue

src/Quartz/Simpl/RAMJobStore.cs
Where possible, avoid interface calls in **RAMJobStore**.
=> RAMJobStore: avoid interface calls

docs/documentation/quartz-3.x/tutorial/more-about-triggers.md
=> docs: (Triggers) Be explicit about trigger priority.

docs/documentation/quartz-2.x/tutorial/jobs-and-triggers.md
=> Fix typo in jobs-and-triggers.md

docs/documentation/quartz-3.x/packages/quartz-plugins.md
* fix typo
* specify invariant culture
=> docs: fix JobInterruptMonitorPlugin code example

src/Quartz/Impl/Calendar/DailyCalendar.cs
Add InvertTimeRange to Clone method
=> Include InvertTimeRange property in DailyCalendar.Clone

src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs
Serilog emits a warning about this
=> Remove unused log parameter

changelog.md, src/Quartz.Extensions.DependencyInjection/QuartzOptions.cs
=> Fix .NET 7 Options processing compatibility in DI

Quartz.sln.DotSettings, src/Quartz.Examples/09_TriggeringAJobUsingJobListeners/SimpleJob1Listener.cs, src/Quartz.Examples/quartz_jobs.xml, src/Quartz.Extensions.DependencyInjection/Simpl/MicrosoftDependencyInjectionJobFactory.cs, src/Quartz.Jobs/SPI/IDirectoryProvider.cs, src/Quartz.Server/SampleJob.cs, src/Quartz.Tests.Integration/Xml/TestData/ComplexCron.xml, src/Quartz.Tests.Integration/Xml/TestData/RichConfiguration.xml, src/Quartz.Tests.Integration/Xml/TestData/RichConfiguration_20.xml, src/Quartz/Impl/Matchers/StringOperator.cs, src/Quartz/Impl/Triggers/AbstractTrigger.cs, src/Quartz/Simpl/TaskSchedulingThreadPool.cs
=> Fix spelling.

src/Directory.Build.props, src/Quartz.Examples/Quartz.Examples.csproj, src/Quartz.Jobs/Quartz.Jobs.csproj, src/Quartz.Plugins.TimeZoneConverter/Quartz.Plugins.TimeZoneConverter.csproj, src/Quartz.Plugins/Quartz.Plugins.csproj, src/Quartz.Serialization.Json/Quartz.Serialization.Json.csproj, src/Quartz.Server/Quartz.Server.csproj, src/Quartz/Quartz.csproj
Set Min target net version 4.7.2  
Reference #1549
=> Set Minimum target framework 4.7.2

src/Quartz.Tests.Unit/SchedulerTest.cs, src/Quartz.Tests.Unit/Simpl/RAMJobStoreTest.cs, src/Quartz/Simpl/RAMJobStore.cs
=> Make RAMJobStore.RemoveJobInternal return true even if job has no triggers

src/Quartz/SchedulerBuilder.cs
=> Add UseMySqlConnector overload for DB configuration

src/Quartz/Impl/JobType.cs
based on feedback from #1610 PR
- Improve documentation
- Move logic into the constructor
- Remove ignored field initializer
=> refactor (JobType)

changelog.md, src/Quartz.Tests.Unit/Impl/Calendar/DailyCalendarTest.cs, src/Quartz/Impl/Calendar/DailyCalendar.cs
=> Fix DailyCalendar to include first and last millisecond of day

src/Quartz.Tests.Unit/SchedulerBuilderTest.cs, src/Quartz/SchedulerBuilder.cs
=> Support DataSource name configuration

src/Quartz.Extensions.DependencyInjection/IServiceCollectionQuartzConfigurator.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionQuartzConfigurator.cs
I need to use custom job store, but DI extension don't have any method for that.
=> add "UsePersistentStore<T> where T : IJobStore" in DI Extension to main

.gitignore, changelog.md, docs/documentation/quartz-3.x/packages/microsoft-di-integration.md, docs/documentation/quartz-3.x/quick-start.md, package-lock.json, src/Quartz.Examples.AspNetCore/Startup.cs, src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs, src/Quartz.Tests.Unit/SchedulerBuilderTest.cs, src/Quartz/Impl/AdoJobStore/AdoConstants.cs, src/Quartz/Impl/AdoJobStore/JobStoreCMT.cs, src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs, src/Quartz/Impl/AdoJobStore/JobStoreTX.cs, src/Quartz/Impl/AdoJobStore/StdAdoDelegate.cs, src/Quartz/SchedulerBuilder.cs
=> Validate database schema during scheduler initialization

docs/.vuepress/config.js, docs/documentation/quartz-3.x/how-tos/one-off-job.md, docs/documentation/quartz-3.x/tutorial/simpletriggers.md
The goal of this PR is to document how to schedule a one-off job. I would also like this page to include any other considerations when building a one-shot job.
Notably, how to best deal with failure. I've been running into one shot jobs that are hanging around in an error state. I'm not sure how to best handle that. So please lay the comments down on me in this PR and I'll happily update the docs!
=> Add how to schedule a one off job

docs/documentation/quartz-3.x/packages/quartz-plugins.md, docs/documentation/quartz-4.x/packages/quartz-plugins.md
=> Update quartz-plugins.md - Fix typo plgin -> plugin

.github/workflows/build.yml, .github/workflows/pr.yml, .nuke/build.schema.json, build/Build.cs, build/_build.csproj, changelog.md, docker-compose.yml, src/Quartz.Examples.AspNetCore/Quartz.Examples.AspNetCore.csproj, src/Quartz.Examples.AspNetCore/Startup.cs, src/Quartz.Examples.AspNetCore/appsettings.json, src/Quartz.Extensions.DependencyInjection/ServiceCollectionSchedulerFactory.cs, src/Quartz.Tests.Integration/Quartz.Tests.Integration.csproj, src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj, src/Quartz/Impl/StdSchedulerFactory.cs
=> Fix named connection string resolution from appsettings.json

changelog.md, src/Quartz/Quartz.csproj
=> Upgrade to System.Configuration.ConfigurationManager 5.0.0

src/Quartz.Examples.AspNetCore/CustomSqlServerConnectionProvider.cs, src/Quartz.Examples.AspNetCore/Startup.cs, src/Quartz/Impl/StdSchedulerFactory.cs
=> Fix configuration handling for custom DB provider

src/Quartz/JobDataMap.cs
=> Actually return Guid in JobDataMap.TryGetGuidValue

changelog.md, src/Quartz.Serialization.Json/Calendars/CronCalendarSerializer.cs, src/Quartz.Serialization.Json/Calendars/DailyCalendarSerializer.cs, src/Quartz.Serialization.Json/Converters/CalendarConverter.cs, src/Quartz.Serialization.Json/Converters/CronExpressionConverter.cs, src/Quartz.Serialization.Json/Quartz.Serialization.Json.csproj, src/Quartz.Server/Quartz.Server.csproj
=> Upgrade to Newtonsoft.Json 13.0.1

src/Quartz/Util/DBConnectionManager.cs
A small possible optimization I noticed was to update `DbConnectionManager` to use `ConcurrentDictionary<>` instead of `Dictionary<>` and a custom synclock as `ConcurrentDictionary` will lock at the bucket level instead of collection level.
A sample benchmark run of `GetDbProvider()` called single-threaded:
```
BenchmarkDotNet=v0.13.2, OS=Windows 11 (10.0.22621.963)
Intel Core i7-8565U CPU 1.80GHz (Whiskey Lake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.101
[Host]     : .NET 7.0.1 (7.0.122.56804), X64 RyuJIT AVX2
DefaultJob : .NET 7.0.1 (7.0.122.56804), X64 RyuJIT AVX2
|             Method |  N |     Mean |    Error |   StdDev |   Median | Ratio | RatioSD | Allocated | Alloc Ratio |
|------------------- |--- |---------:|---------:|---------:|---------:|------:|--------:|--------- …
```
=> Use ConcurrentDictionary in DbConnectionManager

docs/documentation/quartz-2.x/tutorial/crontrigger.md, docs/documentation/quartz-3.x/tutorial/crontrigger.md, docs/documentation/quartz-3.x/tutorial/crontriggers.md
- Resolves #1891
- Minor casing fix.
=> doc (3.x): Add missing crontrigger markdown for 3.x

src/Directory.Packages.props, src/Quartz.Examples/Logging.cs, src/Quartz.Examples/Nlog.config, src/Quartz.Examples/Program.cs, src/Quartz.Examples/Quartz.Examples.csproj
Add an example on using NLog and filtering out Quartz.* namespace messages   relates to #1911 
- Bump packages in example project.
- Microsoft.Extensions.Logging was 5 is now 6
=> Add logging example using NLog

src/Quartz.Extensions.DependencyInjection/Simpl/MicrosoftDependencyInjectionJobFactory.cs, src/Quartz/IJobWrapper.cs, src/Quartz/Impl/JobExecutionContextImpl.cs
This PR cherry picks #1581 into the 3.x branch, to make it available in the next 3.x release.
=> Create IJobWrapper interface and let ScopedJob implement it (#1581)

src/Quartz.Tests.Unit/Impl/AdoJobStore/StdAdoDelegateTest.cs, src/Quartz/Impl/AdoJobStore/StdAdoDelegate.Jobs.cs
Here's the [discussion](https://github.com/quartznet/quartznet/discussions/1921). This is a PR for `main`-branch.
PR for `3.x` is on it's way.
=> Add missing "disallow concurrency" materialization for jobs

src/Quartz.Tests.Unit/Impl/AdoJobStore/StdAdoDelegateTest.cs, src/Quartz/Impl/AdoJobStore/StdAdoConstants.cs
https://github.com/quartznet/quartznet/discussions/1921
https://github.com/quartznet/quartznet/pull/1923
=> Fix SqlSelectJobDetail to include IS_NONCONCURRENT

docs/documentation/quartz-3.x/configuration/reference.md, docs/documentation/quartz-3.x/packages/microsoft-di-integration.md
Fixed a typo and added a crucial tip about configuration through appsettings.json
=> A couple of amendments to the documentations

.vscode/spellright.dict, docs/documentation/quartz-2.x/tutorial/crontrigger.md, docs/documentation/quartz-3.x/configuration/reference.md, docs/documentation/quartz-3.x/how-tos/crontrigger.md, docs/documentation/quartz-3.x/packages/quartz-3rd-party-plugins.md, docs/documentation/quartz-3.x/tutorial/crontrigger.md, docs/documentation/quartz-3.x/tutorial/crontriggers.md, docs/documentation/quartz-3.x/tutorial/scheduler-builder.md, docs/documentation/quartz-4.x/configuration/reference.md, docs/documentation/quartz-4.x/how-tos/crontrigger.md, docs/documentation/quartz-4.x/packages/quartz-3rd-party-plugins.md, docs/documentation/quartz-4.x/tutorial/crontrigger.md, docs/documentation/quartz-4.x/tutorial/crontriggers.md
* Pretty format markdown tables
* Add 3rd party links
=> Documentation: format tables, add additional 3rd party links

src/Directory.Packages.props
=> task: Bump nuget packages

src/Directory.Packages.props
Packages with vulnerabilities have been detected See advisory below: Related Actions and Settings: -
- https://github.com/advisories/GHSA-5pm2-9mr2-3frq (Severity: High) 
- https://devhub.checkmarx.com/cve-details/CVE-2023-21893
=> fix: Update oracle packages to remove vulnerability.

.nuke/build.schema.json, build/Build.cs, build/_build.csproj
The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-DOTNET-SYSTEMDRAWINGCOMMON-3063427
- https://snyk.io/vuln/SNYK-DOTNET-NEWTONSOFTJSON-2774678
- https://snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTENCODINGSWEB-1253267
=> fix: Update Nuke to 7.0.2 to reduce vulnerabilities

changelog.md, src/Quartz.Tests.Integration/Core/RecoverJobsTest.cs, src/Quartz.Tests.Integration/Impl/AdoJobStore/JobStoreSupportTest.cs, src/Quartz.Tests.Integration/JobMaintenanceTests.cs, src/Quartz.Tests.Integration/Xml/XMLSchedulingDataProcessorTest.cs, src/Quartz.Tests.Unit/Impl/AdoJobStore/JobStoreCMTTest.cs, src/Quartz.Tests.Unit/Impl/AdoJobStore/JobStoreSupportTest.cs, src/Quartz/Impl/AdoJobStore/JobStoreCMT.cs, src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs, src/Quartz/Impl/AdoJobStore/JobStoreTX.cs
=> Use ConnectAsync instead of Connect in job stores

src/Quartz.Extensions.Hosting/QuartzHostedService.cs
=> Change QuartzHostedService from internal to public

.github/workflows/build.yml, .github/workflows/pr-tests-integration-postgres.yml, .github/workflows/pr-tests-unit.yml, .nuke/build.schema.json, README.md, build/Build.Publish.cs, build/Build.cs, build/_build.csproj, changelog.md
=> Switch to using feedz.io for pre-release builds

docs/.vuepress/configs/sidebar/en.ts, docs/documentation/quartz-3.x/how-tos/reschedule-jobs.md, docs/documentation/quartz-3.x/how-tos/rescheduling-jobs.md
Please leave any and all feedback that can make this page better. I'm happy to go through all the revisions needed. :) This was super helpful to get me to think about things via different approaches.
=> Add some documentation about how to think about rescheduling jobs

src/Quartz.Tests.Unit/Impl/Calendar/DailyCalendarTest.cs, src/Quartz/Impl/Calendar/DailyCalendar.cs
=> Ensure that the DailyCalendar use the same TimeZone offset for all the checks

src/Quartz.Tests.Unit/SchedulerTest.cs
EDIT: Improvement to test already done in `main` branch.
This is now just a backport of that change to `3.x` branch
As seen in an unrelated PR and the scheduler test failed, expecting a null value for priorRun, but received one. 
https://github.com/quartznet/quartznet/actions/runs/6061704354/job/16447189544
```cs
::error file=D:\a\quartznet\quartznet\src\Quartz.Tests.Unit\Quartz.Tests.Unit.csproj,title=ReschedulingTriggerShouldKeepOriginalNextFireTime::Expected: null%0D%0A  But was:  2023-09-03 01:40:25.5395791+00:00
Failed ReschedulingTriggerShouldKeepOriginalNextFireTime [216 ms]
Error Message:
Expected: null
But was:  2023-09-03 01:40:25.5395791+00:00
Stack Trace:
at Quartz.Tests.Unit.SchedulerTest.ReschedulingTriggerShouldKeepOriginalNextFireTime() in …
```
=> Backport test changes to  ReschedulingTriggerShouldKeepOriginalNextFireTime from main to 3.x

build/Build.CI.GitHubActions.cs, build/Build.cs, changelog.md, src/Quartz.Examples.Worker/Program.cs, src/Quartz.Examples.Worker/Quartz.Examples.Worker.csproj, src/Quartz.Extensions.DependencyInjection/IServiceCollectionQuartzConfigurator.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionQuartzConfigurator.cs, src/Quartz.Tests.Unit/Impl/StdSchedulerFactoryTest.cs, src/Quartz/Impl/StdSchedulerFactory.cs, src/Quartz/JobBuilder.cs, src/Quartz/Quartz.csproj, src/Quartz/SchedulerBuilder.cs
* annotate types with requirement for access against public constructors and methods
* allow disabling configuration validation via strongly-typed configuration
=> Improve trimming compatibility

changelog.md, src/Quartz.Examples.AspNetCore/CustomTypeLoader.cs, src/Quartz.Examples.AspNetCore/Startup.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionQuartzConfigurator.cs, src/Quartz.Plugins/Plugin/Xml/XMLSchedulingDataProcessorPlugin.cs, src/Quartz.Plugins/PluginConfigurationExtensions.cs, src/Quartz/IPropertyConfigurer.cs, src/Quartz/Impl/StdSchedulerFactory.cs
=> Support injecting dependencies to XMLSchedulingDataProcessorPlugin

build/Build.cs, changelog.md, src/Quartz.Examples.AspNetCore/ExampleJob.cs, src/Quartz.Examples.AspNetCore/Quartz.Examples.AspNetCore.csproj, src/Quartz.Examples.AspNetCore/Startup.cs, src/Quartz.Extensions.DependencyInjection/QuartzOptions.cs
=> Enable trimmed publish for ASP.NET Core example

src/Quartz/Configuration/ServiceCollectionExtensions.cs
The word 'shoud' has been corrected to 'should'.
=> fix: typo in comment, 'shoud' is missing an 'l'

docs/documentation/quartz-3.x/packages/microsoft-di-integration.md, docs/documentation/quartz-3.x/tutorial/using-quartz.md
Summary of the changes
- Remove obsolete code
- Update tip
Related: https://github.com/quartznet/quartznet/pull/2085
=> Remove UseMicrosoftDependencyInjectionJobFactory in tutorial

build.ps1, build.sh, build/_build.csproj, src/Directory.Packages.props
* update vulnerable Microsoft.Data.SqlClient
=> Upgrade to NUKE 8

docs/documentation/quartz-3.x/tutorial/overview.md
- Fixed an incorrect possessive contraction
- Added a missing infinitive marker
- Revised list sequencing / oxford comma usage (improper compound item)
- Revised em dash usage and sentence clarity
=> Revise grammar in overview.md

docs/documentation/best-practices.md
ScheduleJobs hasn't been mentioned anywhere in documentation, despite it being a very handy method to use
=> Update best-practices.md, adding "ScheduleJobs" method

docs/.vuepress/config.ts, docs/faq.md, docs/mailing_list.md, docs/migration_guide.md, docs/tutorial/README.md, docs/tutorial/lesson_1.md, docs/tutorial/lesson_10.md, docs/tutorial/lesson_11.md, docs/tutorial/lesson_12.md, docs/tutorial/lesson_2.md, docs/tutorial/lesson_3.md, docs/tutorial/lesson_4.md, docs/tutorial/lesson_5.md, docs/tutorial/lesson_6.md, docs/tutorial/lesson_7.md, docs/tutorial/lesson_8.md, docs/tutorial/lesson_9.md, package-lock.json, package.json
- Update VuePress from beta to RC7
- Use redirectPlugin
=> DOCS: Update VuePress to 2.0-RC7

docs/.vuepress/configs/sidebar/en.ts, docs/documentation/quartz-3.x/db/index.md, docs/documentation/quartz-3.x/tutorial/job-stores.md
Ok, this is an attempt to put together some docs on the tables. I'm starting to learn them a bit more as I need to debug things and wanted to share my learnings.
1. Where should we put this documentation in the TOC? I just picked a spot but would love any feedback.
2. I for the most part focused on documenting my current questions and how I see things.
3. I'm thinking I'd like more documentation on the trigger types and how they map to the tables. 🤔 
What else can we add?
=> Adding some docs about the database support in quartz

src/Quartz.Tests.Unit/Simpl/MicrosoftDependencyInjectionJobFactoryTest.cs, src/Quartz/IJobWrapper.cs, src/Quartz/Simpl/MicrosoftDependencyInjectionJobFactory.cs, src/Quartz/Simpl/PropertySettingJobFactory.cs, src/Quartz/Simpl/SimpleJobFactory.cs
Changes
- change IJobWrapper to be public
Fixes #2310
=> make IJobWrapper public

CONTRIBUTING.md
Added test command from `build.yml`.
WIP: Tests are failing on my computer. Additional information in the new **Testing** section may be required.
=> Add testing section to CONTRIBUTING.md

src/Quartz.HttpClient/HttpClientOptions.cs
HttpClient construction. Add separate error messages to better indicate the Invalid state.
Relates to #2410
=> HttpClient construction. Add separate error messages to better indicate the Invalid state.

docs/documentation/quartz-3.x/packages/system-text-json.md, src/Quartz.Serialization.SystemTextJson/Simpl/SystemTextJsonObjectSerializer.cs
=> Don't create intermediate MemoryStream in SystemTextJsonObjectSerializer

src/Quartz.Benchmark/Directory.Build.props, src/Quartz.Benchmark/RAMJobStoreBenchmark.cs
* use await like real calling code
* fix other issues
* fix configuration
=> Improve RAMJobStoreBenchmark

Directory.Packages.props, src/Quartz.Tests.Unit/Extensions/DependencyInjection/ServiceCollectionExtensionsTests.cs, src/Quartz.Tests.Unit/Quartz.Tests.Unit.csproj, src/Quartz/Configuration/ServiceCollectionExtensions.cs, src/Quartz/Impl/AdoJobStore/Common/DataSourceDbProvider.cs, src/Quartz/SchedulerBuilder.cs
=> Add support for DbDataSource

src/Quartz/Simpl/RAMJobStore.cs
Using `lock` doesn't go well with async paradigm.
=> SemaphoreSlim for RAMJobStore locking

src/Quartz.Serialization.Json/Converters/TriggerConverter.cs, src/Quartz.Serialization.Json/JsonConfigurationExtensions.cs, src/Quartz.Serialization.Json/Simpl/JsonObjectSerializer.cs, src/Quartz.Serialization.Json/Triggers/CalendarIntervalTriggerSerializer.cs, src/Quartz.Serialization.Json/Triggers/CronTriggerSerializer.cs, src/Quartz.Serialization.Json/Triggers/DailyTimeIntervalTriggerSerializer.cs, src/Quartz.Serialization.Json/Triggers/SimpleTriggerSerializer.cs, src/Quartz.Serialization.Json/Triggers/TriggerSerializer.cs, src/Quartz.Serialization.Json/Util/SerializationExtensions.cs, src/Quartz.Serialization.SystemTextJson/Converters/TriggerConverter.cs, src/Quartz.Serialization.SystemTextJson/Triggers/CalendarIntervalTriggerSerializer.cs, src/Quartz.Serialization.SystemTextJson/Triggers/CronTriggerSerializer.cs, src/Quartz.Serialization.SystemTextJson/Triggers/DailyTimeIntervalTriggerSerializer.cs, src/Quartz.Serialization.SystemTextJson/Triggers/SimpleTriggerSerializer.cs, src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs, src/Quartz.Tests.Integration/Impl/RemoteSchedulerSmokeTest.cs, src/Quartz.Tests.Integration/Impl/SmokeTestPerformer.cs, src/Quartz.Tests.Unit/Simpl/JsonObjectSerializerTest.cs
=> Add trigger serializers for Newtonsoft based serializer

src/Quartz.Tests.Unit/CronExpressionTest.cs, src/Quartz/CronExpression.cs
=> ISSUE #2485

src/Quartz.Extensions.DependencyInjection/ServiceCollectionSchedulerFactory.cs, src/Quartz.Extensions.Hosting/QuartzHostedService.cs, src/Quartz.Tests.Unit/QuartzHostedServiceTests.cs, src/Quartz/Core/QuartzScheduler.cs, src/Quartz/Impl/StdSchedulerFactory.cs
=> Make scheduler registration cleanup more robust during shutdown

docs/documentation/quartz-4.x/packages/microsoft-di-integration.md, docs/documentation/quartz-4.x/quick-start.md, src/Quartz.Examples/13_ClusteringJobsExecution/ClusteringJobsExecutionExample.cs, src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs, src/Quartz.Tests.Unit/Extensions/DependencyInjection/ServiceCollectionExtensionsTests.cs, src/Quartz.Tests.Unit/SchedulerBuilderTest.cs, src/Quartz/Impl/AdoJobStore/Common/DataSourceDbProvider.cs, src/Quartz/SchedulerBuilder.cs
=> Make data source name required for database integration

src/Quartz.Extensions.DependencyInjection/ServiceCollectionExtensions.cs, src/Quartz.Extensions.DependencyInjection/ServiceCollectionSchedulerFactory.cs, src/Quartz.Tests.Integration/AdoSchedulerTest.cs, src/Quartz.Tests.Integration/Impl/AdoJobStore/AdoJobStoreSmokeTest.cs, src/Quartz.Tests.Integration/JobDataMapStorageTest.cs, src/Quartz.Tests.Integration/TestHelpers/SchedulerHelper.cs, src/Quartz/Core/QuartzScheduler.cs, src/Quartz/Core/QuartzSchedulerResources.cs, src/Quartz/Impl/DirectSchedulerFactory.cs, src/Quartz/Impl/SchedulerRepository.cs, src/Quartz/Impl/StdSchedulerFactory.cs
Make `SchedulerRepository` internal
fixes #1453
=> Change scheduler repository to be singleton scoped to DI under MS DI integration

src/Quartz/CronExpression.cs, src/Quartz/ThrowHelper.cs
Refactors on `CronExpression` class (mostly around reducing method complexity).
No functional changes.
=> Refactor CronExpression class

src/Quartz.Tests.Unit/Core/QuartzRandomTest.cs, src/Quartz/Core/QuartzRandom.cs, src/Quartz/Core/QuartzScheduler.cs, src/Quartz/Core/QuartzSchedulerThread.cs
This PR replaces obsolete `RNGCryptoServiceProvider` with `RandomNumberGenerator`. `QuartzRandom` class is static now
=> Make QuartzRandom class static

docs/documentation/quartz-3.x/how-tos/rescheduling-jobs.md
=> Fix code example for self-rescheduling

src/Quartz.Tests.Unit/Impl/AdoJobStore/StdAdoConstantsTest.cs, src/Quartz/Impl/AdoJobStore/StdAdoConstants.cs
=> Use invariant culture for StdAdoConstants SQL formatting

docs/documentation/quartz-1.x/tutorial/configuration-resource-usage-and-scheduler-factory.md, docs/documentation/quartz-1.x/tutorial/crontriggers.md, docs/documentation/quartz-1.x/tutorial/job-stores.md, docs/documentation/quartz-1.x/tutorial/more-about-triggers.md, docs/documentation/quartz-1.x/tutorial/trigger-and-job-listeners.md, docs/documentation/quartz-2.x/quick-start.md, docs/documentation/quartz-2.x/tutorial/configuration-resource-usage-and-scheduler-factory.md, docs/documentation/quartz-2.x/tutorial/crontrigger.md, docs/documentation/quartz-2.x/tutorial/crontriggers.md, docs/documentation/quartz-2.x/tutorial/job-stores.md, docs/documentation/quartz-3.x/db/index.md, docs/documentation/quartz-3.x/how-tos/crontrigger.md, docs/documentation/quartz-3.x/packages/json-serialization.md, docs/documentation/quartz-3.x/packages/system-text-json.md, docs/documentation/quartz-3.x/tutorial/crontrigger.md, docs/documentation/quartz-3.x/tutorial/job-stores.md, docs/documentation/quartz-4.x/how-tos/crontrigger.md, docs/documentation/quartz-4.x/tutorial/crontrigger.md, docs/documentation/quartz-4.x/tutorial/job-stores.md, package-lock.json, package.json
- Fix documentation for cronformat, incorrectly broke in previous lint pass.  Resolves #2583
- Bump markdownlint package
- Reduce other markdownlint violations.
=> Fix documentation for cron format

src/Quartz.OpenTracing/QuartzDiagnostic.cs, src/Quartz.OpenTracing/QuartzDiagnosticOptions.cs, src/Quartz/Logging/IJobDiagnosticData.cs, src/Quartz/Logging/JobDiagnosticData.cs
=> OpenTracing: using IJobDiagnosticData instead of IJobExecutionContext

docs/documentation/quartz-3.x/packages/quartz-3rd-party-plugins.md, docs/documentation/quartz-4.x/packages/quartz-3rd-party-plugins.md
I cooked up https://github.com/Hawxy/Weasel.Quartz a few months ago but forgot to add it here.
=> Add a link to the Weasel.Quartz library

src/Quartz/Core/QuartzSchedulerThread.cs
=> Don't transition triggers to error state on scheduler shutdown/disposal
